export function getArmorPassive(displayName) {
  return ARMOR_PASSIVES.find((item) => item.displayName === displayName);
}

export const ARMOR_PASSIVES = [
  {
    displayName: "Advanced Filtration",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond10",
    internalName: "advancedfiltration",
    imageUrl: "armorpassives/advancedfiltration.png",
    tier: "b",
  },
  {
    displayName: "Acclimated",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond18",
    internalName: "acclimated",
    imageUrl: "armorpassives/inflammable.png",
    tier: "d",
  },
  {
    displayName: "Democracy Protects",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "none",
    internalName: "democracyprotects",
    imageUrl: "armorpassives/democracyprotects.png",
    tier: "a",
  },
  {
    displayName: "Electrical Conduit",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond5",
    internalName: "electricalconduit",
    imageUrl: "armorpassives/electricalconduit.png",
    tier: "d",
  },
  {
    displayName: "Engineering Kit",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond3",
    internalName: "engineeringkit",
    imageUrl: "armorpassives/engineeringkit.png",
    tier: "s",
  },
  {
    displayName: "Extra Padding",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "none",
    internalName: "extrapadding",
    imageUrl: "armorpassives/extrapadding.png",
    tier: "a",
  },
  {
    displayName: "Fortified",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond6",
    internalName: "fortified",
    imageUrl: "armorpassives/fortified.png",
    tier: "b",
  },
  {
    displayName: "Inflammable",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond9",
    internalName: "inflammable",
    imageUrl: "armorpassives/inflammable.png",
    tier: "b",
  },
  {
    displayName: "Med-Kit",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond3",
    internalName: "medkit",
    imageUrl: "armorpassives/medkit.png",
    tier: "s",
  },
  {
    displayName: "Peak Physique",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond8",
    internalName: "peakphysique",
    imageUrl: "armorpassives/peakphysique.png",
    tier: "b",
  },
  {
    displayName: "Scout",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond3",
    internalName: "scout",
    imageUrl: "armorpassives/scout.png",
    tier: "b",
  },
  {
    displayName: "Servo-Assisted",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond4",
    internalName: "servoassisted",
    imageUrl: "armorpassives/servoassisted.png",
    tier: "b",
  },
  {
    displayName: "Unflinching",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond11",
    internalName: "unflinching",
    imageUrl: "armorpassives/unflinching.png",
    tier: "a",
  },
  {
    displayName: "Siege Ready",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond12",
    internalName: "siegeready",
    imageUrl: "armorpassives/siegeready.png",
    tier: "a",
  },
  {
    displayName: "Integrated Explosives",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond13",
    internalName: "integratedexplosives",
    imageUrl: "armorpassives/integratedexplosives.png",
    tier: "a",
  },
  {
    displayName: "Gunslinger",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond14",
    internalName: "gunslinger",
    imageUrl: "armorpassives/gunslinger.png",
    tier: "c",
  },
  {
    displayName: "Reinforced Epaulettes",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond15",
    internalName: "reinforcedepaulettes",
    imageUrl: "armorpassives/reinforcedepaulettes.png",
    tier: "b",
  },
  {
    displayName: "Ballistic Padding",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond16",
    internalName: "ballisticpadding",
    imageUrl: "armorpassives/ballisticpadding.png",
    tier: "b",
  },
  {
    displayName: "Adreno-Defibrillator",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond17",
    internalName: "adrenodefibrillator",
    imageUrl: "armorpassives/adrenodefibrillator.png",
    tier: "c",
  },
  {
    displayName: "Feet First",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond19",
    internalName: "feetfirst",
    imageUrl: "armorpassives/feetfirst.png",
    tier: "c",
  },
  {
    displayName: "Desert Stormer",
    type: "Equipment",
    category: "armor",
    tags: ["ArmorPassive"],
    warbondCode: "warbond20",
    internalName: "desertstormer",
    imageUrl: "armorpassives/desertstormer.png",
    tier: "c",
  },
];
