export function getBooster(displayName) {
  return BOOSTERS.find((item) => item.displayName === displayName);
}

export const BOOSTERS = [
  {
    displayName: "Expert Extraction Pilot",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond6",
    internalName: "expertextractionpilot",
    imageUrl: "boosters/expertextractionpilot.png",
    tier: "c",
  },
  {
    displayName: "Dead Sprint",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond11",
    internalName: "deadsprint",
    imageUrl: "boosters/deadsprint.png",
    tier: "b",
  },
  {
    displayName: "Armed Resupply Pods",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond12",
    internalName: "armedresupplypods",
    imageUrl: "boosters/armedresupplypods.png",
    tier: "b",
  },
  {
    displayName: "Experimental Infusion",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond8",
    internalName: "experimentalinfusion",
    imageUrl: "boosters/experimentalinfusion.png",
    tier: "s",
  },
  {
    displayName: "Motivational Shocks",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond7",
    internalName: "motivationalshocks",
    imageUrl: "boosters/motivationalshocks.png",
    tier: "c",
  },
  {
    displayName: "Flexible Reinforcement Budget",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond4",
    internalName: "flexiblereinforcementbudget",
    imageUrl: "boosters/flexiblereinforcementbudget.png",
    tier: "c",
  },
  {
    displayName: "Hellpod Space Optimization",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond3",
    internalName: "hellpodspaceoptimization",
    imageUrl: "boosters/hellpodspaceoptimization.png",
    tier: "s",
  },
  {
    displayName: "Increased Reinforcement Budget",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond3",
    internalName: "increasedreinforcementbudget",
    imageUrl: "boosters/increasedreinforcementbudget.png",
    tier: "c",
  },
  {
    displayName: "Localization Confusion",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond5",
    internalName: "localizationconfusion",
    imageUrl: "boosters/localizationconfusion.png",
    tier: "b",
  },
  {
    displayName: "Muscle Enhancement",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond3",
    internalName: "muscleenhancement",
    imageUrl: "boosters/muscleenhancement.png",
    tier: "a",
  },
  {
    displayName: "Stamina Enhancement",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond3",
    internalName: "staminaenhancement",
    imageUrl: "boosters/staminaenhancement.png",
    tier: "a",
  },
  {
    displayName: "UAV Recon",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond3",
    internalName: "uavrecon",
    imageUrl: "boosters/uavrecon.png",
    tier: "c",
  },
  {
    displayName: "Vitality Enhancement",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond3",
    internalName: "vitalityenhancement",
    imageUrl: "boosters/vitalityenhancement.png",
    tier: "s",
  },
  {
    displayName: "Firebomb Hellpods",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond9",
    internalName: "firebombhellpods",
    imageUrl: "boosters/firebombhellpods.png",
    tier: "d",
  },
  {
    displayName: "Sample Extricator",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond14",
    internalName: "sampleextricator",
    imageUrl: "boosters/sampleextricator.png",
    tier: "d",
  },
  {
    displayName: "Sample Scanner",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond15",
    internalName: "samplescanner",
    imageUrl: "boosters/samplescanner.png",
    tier: "d",
  },
  {
    displayName: "Stun Pods",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond16",
    internalName: "stunpods",
    imageUrl: "boosters/stunpods.png",
    tier: "d",
  },
];
