export function getCape(displayName) {
  return CAPES.find((item) => item.displayName === displayName);
}

export const CAPES = [
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageUrl: "capes/foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Will of the People",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond0",
    internalName: "willofthepeople",
    imageUrl: "capes/willofthepeople.webp",
    tier: "b",
  },
  {
    displayName: "Independence Bringer",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "independencebringer",
    imageUrl: "capes/independencebringer.webp",
    tier: "b",
  },
  {
    displayName: "Liberty's Herald",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "libertysherald",
    imageUrl: "capes/libertysherald.webp",
    tier: "b",
  },
  {
    displayName: "Tideturner",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "tideturner",
    imageUrl: "capes/tideturner.webp",
    tier: "b",
  },
  {
    displayName: "Stars and Suffrage",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "thecapeofstarsandsuffrage",
    imageUrl: "capes/thecapeofstarsandsuffrage.webp",
    tier: "b",
  },
  {
    displayName: "Unblemished Allegiance",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "unblemishedallegiance",
    imageUrl: "capes/unblemishedallegiance.webp",
    tier: "b",
  },
  {
    displayName: "Judgment Day",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "judgmentday",
    imageUrl: "capes/judgmentday.webp",
    tier: "b",
  },
  {
    displayName: "Cresting Honor",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "crestinghonor",
    imageUrl: "capes/crestinghonor.webp",
    tier: "b",
  },
  {
    displayName: "Mantle of True Citizenship",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "mantleoftruecitizenship",
    imageUrl: "capes/mantleoftruecitizenship.webp",
    tier: "b",
  },
  {
    displayName: "Blazing Samaritan",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "blazingsamaritan",
    imageUrl: "capes/blazingsamaritan.webp",
    tier: "b",
  },
  {
    displayName: "Light of Eternal Liberty",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "lightofeternalliberty",
    imageUrl: "capes/lightofeternalliberty.webp",
    tier: "b",
  },
  {
    displayName: "Tyrant Hunter",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond4",
    internalName: "tyranthunter",
    imageUrl: "capes/tyranthunter.webp",
    tier: "b",
  },
  {
    displayName: "Cloak of Posterity's Gratitude",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond4",
    internalName: "cloakofposteritysgratitude",
    imageUrl: "capes/cloakofposteritysgratitude.webp",
    tier: "b",
  },
  {
    displayName: "Drape of Glory",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond4",
    internalName: "drapeofglory",
    imageUrl: "capes/drapeofglory.webp",
    tier: "b",
  },
  {
    displayName: "Bastion of Integrity",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "bastionofintegrity",
    imageUrl: "capes/bastionofintegrity.webp",
    tier: "b",
  },
  {
    displayName: "Botslayer",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond5",
    internalName: "botslayer",
    imageUrl: "capes/botslayer.webp",
    tier: "b",
  },
  {
    displayName: "Martyris Rex",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond5",
    internalName: "martyrisrex",
    imageUrl: "capes/martyrisrex.webp",
    tier: "b",
  },
  {
    displayName: "Agent of Oblivion",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond5",
    internalName: "agentofoblivion",
    imageUrl: "capes/agentofoblivion.webp",
    tier: "b",
  },
  {
    displayName: "Fallen Hero's Vengeance",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "fallenherosvengeance",
    imageUrl: "capes/fallenherosvengeance.webp",
    tier: "b",
  },
  {
    displayName: "Harbinger of True Equality",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond6",
    internalName: "harbingeroftrueequality",
    imageUrl: "capes/harbingeroftrueequality.webp",
    tier: "b",
  },
  {
    displayName: "Eagle's Fury",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond6",
    internalName: "eaglesfury",
    imageUrl: "capes/eaglesfury.webp",
    tier: "b",
  },
  {
    displayName: "Freedom's Tapestry",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond6",
    internalName: "freedomstapestry",
    imageUrl: "capes/freedomstapestry.webp",
    tier: "b",
  },
  {
    displayName: "Dissident's Nightmare",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond7",
    internalName: "dissidentsnightmare",
    imageUrl: "capes/dissidentsnightmare.webp",
    tier: "b",
  },
  {
    displayName: "Rightful Occupier",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond20",
    internalName: "rightfuloccupier",
    imageUrl: "capes/rightfuloccupier.webp",
    tier: "b",
  },
  {
    displayName: "Pinions of Everlasting Glory",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond7",
    internalName: "pinionsofeverlastingglory",
    imageUrl: "capes/pinionsofeverlastingglory.webp",
    tier: "b",
  },
  {
    displayName: "Windswept Wayfinder",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond20",
    internalName: "windsweptwayfinder",
    imageUrl: "capes/windsweptwayfinder.webp",
    tier: "b",
  },
  {
    displayName: "Order of the Venerated Ballot",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond7",
    internalName: "orderoftheveneratedballot",
    imageUrl: "capes/orderoftheveneratedballot.webp",
    tier: "b",
  },
  {
    displayName: "Mark of the Crimson Fang",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond8",
    internalName: "markofthecrimsonfang",
    imageUrl: "capes/markofthecrimsonfang.webp",
    tier: "b",
  },
  {
    displayName: "Executioner's Canopy",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond8",
    internalName: "executionerscanopy",
    imageUrl: "capes/executionerscanopy.webp",
    tier: "b",
  },
  {
    displayName: "Purifying Eclipse",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond9",
    internalName: "purifyingeclipse",
    imageUrl: "capes/purifyingeclipse.webp",
    tier: "b",
  },
  {
    displayName: "The Breach",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond9",
    internalName: "thebreach",
    imageUrl: "capes/thebreach.webp",
    tier: "b",
  },
  {
    displayName: "Standard of Safe Distance",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond10",
    internalName: "standardofsafedistance",
    imageUrl: "capes/standardofsafedistance.webp",
    tier: "b",
  },
  {
    displayName: "Patient Zero's Remembrance",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond10",
    internalName: "patientzerosremembrance",
    imageUrl: "capes/patientzerosremembrance.webp",
    tier: "b",
  },
  {
    displayName: "Cover of Darkness",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "coverofdarkness",
    imageUrl: "capes/coverofdarkness.webp",
    tier: "b",
  },
  {
    displayName: "Pride of the Whistleblower",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond11",
    internalName: "prideofthewhistleblower",
    imageUrl: "capes/prideofthewhistleblower.webp",
    tier: "b",
  },
  {
    displayName: "Proof of Faultless Virtue",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond11",
    internalName: "proofoffaultlessvirtue",
    imageUrl: "capes/proofoffaultlessvirtue.webp",
    tier: "b",
  },
  {
    displayName: "Stone-Wrought Perseverance",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "stonewroughtperserverance",
    imageUrl: "capes/stonewroughtperserverance.webp",
    tier: "b",
  },
  {
    displayName: "Greatcloak of Rebar Resolve",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond12",
    internalName: "greatcloakofrebarresolve",
    imageUrl: "capes/greatcloakofrebarresolve.webp",
    tier: "b",
  },
  {
    displayName: "Holder of the Yellow Line",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond12",
    internalName: "holderoftheyellowline",
    imageUrl: "capes/holderoftheyellowline.webp",
    tier: "b",
  },
  {
    displayName: "Strength in Our Arms",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond18",
    internalName: "strengthinourarms",
    imageUrl: "capes/strengthinourarms.webp",
    tier: "b",
  },
  {
    displayName: "Defender of Our Dream",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond18",
    internalName: "defenderofourdream",
    imageUrl: "capes/defenderofourdream.webp",
    tier: "b",
  },
  {
    displayName: "Vision of Freedom",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "visionoffreedom",
    imageUrl: "capes/visionoffreedom.webp",
    tier: "b",
  },
  {
    displayName: "Eternal Corona",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "eternalcorona",
    imageUrl: "capes/eternalcorona.webp",
    tier: "b",
  },
  {
    displayName: "Fre Liberam",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond13",
    internalName: "freliberam",
    imageUrl: "capes/freliberam.webp",
    tier: "b",
  },
  {
    displayName: "Per Democrasum",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond13",
    internalName: "perdemocrasum",
    imageUrl: "capes/perdemocrasum.webp",
    tier: "b",
  },
  {
    displayName: "Eye of Freedom",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "eyeoffreedom",
    imageUrl: "capes/eyeoffreedom.webp",
    tier: "b",
  },
  {
    displayName: "Emblem of Freedom",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "emblemoffreedom",
    imageUrl: "capes/emblemoffreedom.webp",
    tier: "b",
  },
  {
    displayName: "Veil of the Valorous Vagabond",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "veilofthevalorousvagabond",
    imageUrl: "capes/veilofthevalorousvagabond.webp",
    tier: "b",
  },
  {
    displayName: "Reaper of Bounties",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond14",
    internalName: "reaperofbounties",
    imageUrl: "capes/reaperofbounties.webp",
    tier: "b",
  },
  {
    displayName: "Way of the Bandolier",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond14",
    internalName: "wayofthebandolier",
    imageUrl: "capes/wayofthebandolier.webp",
    tier: "b",
  },
  {
    displayName: "Seal of General Consensus",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "sealofgeneralconsensus",
    imageUrl: "capes/sealofgeneralconsensus.webp",
    tier: "b",
  },
  {
    displayName: "Federation's Embrace",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond15",
    internalName: "federationsembrace",
    imageUrl: "capes/federationsembrace.webp",
    tier: "b",
  },
  {
    displayName: "Humble Regalia",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond15",
    internalName: "humbleregalia",
    imageUrl: "capes/humbleregalia.webp",
    tier: "b",
  },
  {
    displayName: "Badge of Order",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "badgeoforder",
    imageUrl: "capes/badgeoforder.webp",
    tier: "b",
  },
  {
    displayName: "Miranda's Legacy",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond16",
    internalName: "mirandaslegacy",
    imageUrl: "capes/mirandaslegacy.webp",
    tier: "b",
  },
  {
    displayName: "Mother Eagle's Wings",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond16",
    internalName: "mothereagleswings",
    imageUrl: "capes/mothereagleswings.webp",
    tier: "b",
  },
  {
    displayName: "Protector of the Heart",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "protectoroftheheart",
    imageUrl: "capes/protectoroftheheart.webp",
    tier: "b",
  },
  {
    displayName: "Pillars of Freedom",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "pillarsoffreedom",
    imageUrl: "capes/pillarsoffreedom.webp",
    tier: "b",
  },
  {
    displayName: "Conductor of Brilliance",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond17",
    internalName: "conductorofbrilliance",
    imageUrl: "capes/conductorofbrilliance.webp",
    tier: "b",
  },
  {
    displayName: "Over Artifice Triumphant",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond17",
    internalName: "overartificetriumphant",
    imageUrl: "capes/overartificetriumphant.webp",
    tier: "b",
  },
  {
    displayName: "Schema Laid Bare",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "schemalaidbare",
    imageUrl: "capes/schemalaidbare.webp",
    tier: "b",
  },
  {
    displayName: "Ingress-81",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "ingress81",
    imageUrl: "capes/ingress81.webp",
    tier: "b",
  },
  {
    displayName: "Honored Heirloom",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond19",
    internalName: "honoredheirloom",
    imageUrl: "capes/honoredheirloom.webp",
    tier: "b",
  },
  {
    displayName: "Eye of the Clandestine",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond19",
    internalName: "eyeoftheclandestine",
    imageUrl: "capes/eyeoftheclandestine.webp",
    tier: "b",
  },
];
