export function getHelmet(displayName) {
  return HELMETS.find((item) => item.displayName === displayName);
}

export const HELMETS = [
  {
    displayName: "AF-50 Noxious Ranger",
    type: "Equipment",
    category: "helmet",
    tags: ["Light"],
    warbondCode: "warbond10",
    internalName: "af50noxiousranger",
    imageUrl: "helmets/af50noxiousranger.webp",
    tier: "b",
  },
  {
    displayName: "AC-2 Obedient",
    type: "Equipment",
    category: "helmet",
    tags: ["Light"],
    warbondCode: "warbond18",
    internalName: "ac2obedient",
    imageUrl: "helmets/ac2obedient.webp",
    tier: "b",
  },
  {
    displayName: "SR-24 Street Scout",
    type: "Equipment",
    category: "helmet",
    tags: ["Light"],
    warbondCode: "warbond12",
    internalName: "sr24streetscout",
    imageUrl: "helmets/sr24streetscout.webp",
    tier: "b",
  },
  {
    displayName: "SR-18 Road Block",
    type: "Equipment",
    category: "helmet",
    tags: ["Heavy"],
    warbondCode: "warbond12",
    internalName: "sr18roadblock",
    imageUrl: "helmets/sr18roadblock.webp",
    tier: "b",
  },
  {
    displayName: "B-08 Light Gunner",
    type: "Equipment",
    category: "helmet",
    tags: ["Light"],
    warbondCode: "warbond1",
    internalName: "b08lightgunner",
    imageUrl: "helmets/b08lightgunner.webp",
    tier: "b",
  },
  {
    displayName: "CE-07 Demolition Specialist",
    type: "Equipment",
    category: "helmet",
    tags: ["Light"],
    warbondCode: "warbond6",
    internalName: "ce07demolitionspecialist",
    imageUrl: "helmets/ce07demolitionspecialist.webp",
    tier: "b",
  },
  {
    displayName: "CE-67 Titan",
    type: "Equipment",
    category: "helmet",
    tags: ["Light"],
    warbondCode: "warbond1",
    internalName: "ce67titan",
    imageUrl: "helmets/ce67titan.webp",
    tier: "b",
  },
  {
    displayName: "CE-74 Breaker",
    type: "Equipment",
    category: "helmet",
    tags: ["Light"],
    warbondCode: "warbond1",
    internalName: "ce74breaker",
    imageUrl: "helmets/ce74breaker.webp",
    tier: "b",
  },
  {
    displayName: "CM-21 Trench Paramedic",
    type: "Equipment",
    category: "helmet",
    tags: ["Light"],
    warbondCode: "warbond1",
    internalName: "cm21trenchparamedic",
    imageUrl: "helmets/cm21trenchparamedic.webp",
    tier: "b",
  },
  {
    displayName: "CW-4 Arctic Ranger",
    type: "Equipment",
    category: "helmet",
    tags: ["Light"],
    warbondCode: "warbond7",
    internalName: "cw4arcticranger",
    imageUrl: "helmets/cw4arcticranger.webp",
    tier: "b",
  },
  {
    displayName: "EX-00 Prototype X",
    type: "Equipment",
    category: "helmet",
    tags: ["Light"],
    warbondCode: "warbond5",
    internalName: "ex00prototypex",
    imageUrl: "helmets/ex00prototypex.webp",
    tier: "b",
  },
  {
    displayName: "FS-37 Ravager",
    type: "Equipment",
    category: "helmet",
    tags: ["Light"],
    warbondCode: "warbond1",
    internalName: "fs37ravager",
    imageUrl: "helmets/fs37ravager.webp",
    tier: "b",
  },
  {
    displayName: "FS-38 Eradicator",
    type: "Equipment",
    category: "helmet",
    tags: ["Light"],
    warbondCode: "warbond1",
    internalName: "fs38eradicator",
    imageUrl: "helmets/fs38eradicator.webp",
    tier: "b",
  },
  {
    displayName: "I-09 Heatseeker",
    type: "Equipment",
    category: "helmet",
    tags: ["Light"],
    warbondCode: "warbond9",
    internalName: "i09heatseeker",
    imageUrl: "helmets/i09heatseeker.webp",
    tier: "b",
  },
  {
    displayName: "PH-9 Predator",
    type: "Equipment",
    category: "helmet",
    tags: ["Light"],
    warbondCode: "warbond8",
    internalName: "ph9predator",
    imageUrl: "helmets/ph9predator.webp",
    tier: "b",
  },
  {
    displayName: "SC-30 Trailblazer Scout",
    type: "Equipment",
    category: "helmet",
    tags: ["Light"],
    warbondCode: "warbond3",
    internalName: "sc30trailblazerscout",
    imageUrl: "helmets/sc30trailblazerscout.webp",
    tier: "b",
  },
  {
    displayName: "SC-34 Infiltrator",
    type: "Equipment",
    category: "helmet",
    tags: ["Light"],
    warbondCode: "warbond3",
    internalName: "sc34infiltrator",
    imageUrl: "helmets/sc34infiltrator.webp",
    tier: "b",
  },
  {
    displayName: "SC-37 Legionnaire",
    type: "Equipment",
    category: "helmet",
    tags: ["Light"],
    warbondCode: "warbond1",
    internalName: "sc37legionnaire",
    imageUrl: "helmets/sc37legionnaire.webp",
    tier: "b",
  },
  {
    displayName: "UF-16 Inspector",
    type: "Equipment",
    category: "helmet",
    tags: ["Light"],
    warbondCode: "warbond11",
    internalName: "uf16inspector",
    imageUrl: "helmets/uf16inspector.webp",
    tier: "b",
  },
  {
    displayName: "AF-02 Haz-Master",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond10",
    internalName: "af02hazmaster",
    imageUrl: "helmets/af02hazmaster.webp",
    tier: "b",
  },
  {
    displayName: "AF-91 Field Chemist",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond1",
    internalName: "af91fieldchemist",
    imageUrl: "helmets/af91fieldchemist.webp",
    tier: "b",
  },
  {
    displayName: "B-01 Tactical",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "none",
    internalName: "b01tactical",
    imageUrl: "helmets/b01tactical.webp",
    tier: "b",
  },
  {
    displayName: "B-24 Enforcer",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond1",
    internalName: "b24enforcer",
    imageUrl: "helmets/b24enforcer.webp",
    tier: "b",
  },
  {
    displayName: "CE-27 Ground Breaker",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond6",
    internalName: "ce27groundbreaker",
    imageUrl: "helmets/ce27groundbreaker.webp",
    tier: "b",
  },
  {
    displayName: "CE-35 Trench Engineer",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond3",
    internalName: "ce35trenchengineer",
    imageUrl: "helmets/ce35trenchengineer.webp",
    tier: "b",
  },
  {
    displayName: "CE-81 Juggernaut",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond1",
    internalName: "ce81juggernaut",
    imageUrl: "helmets/ce81juggernaut.webp",
    tier: "b",
  },
  {
    displayName: "CM-09 Bonesnapper",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond3",
    internalName: "cm09bonesnapper",
    imageUrl: "helmets/cm09bonesnapper.webp",
    tier: "b",
  },
  {
    displayName: "CM-10 Clinician",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond1",
    internalName: "cm10clinician",
    imageUrl: "helmets/cm10clinician.webp",
    tier: "b",
  },
  {
    displayName: "CM-14 Physician",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond3",
    internalName: "cm14physician",
    imageUrl: "helmets/cm14physician.webp",
    tier: "b",
  },
  {
    displayName: "CW-9 White Wolf",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond1",
    internalName: "cw9whitewolf",
    imageUrl: "helmets/cw9whitewolf.webp",
    tier: "b",
  },
  {
    displayName: "DP-00 Tactical",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "none",
    internalName: "dp00tactical",
    imageUrl: "helmets/dp00tactical.webp",
    tier: "b",
  },
  {
    displayName: "DP-11 Champion of the People",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond3",
    internalName: "dp11championofthepeople",
    imageUrl: "helmets/dp11championofthepeople.webp",
    tier: "b",
  },
  {
    displayName: "AC-1 Dutiful",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond18",
    internalName: "ac1dutiful",
    imageUrl: "helmets/ac1dutiful.webp",
    tier: "b",
  },
  {
    displayName: "DP-40 Hero of the Federation",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond3",
    internalName: "dp40heroofthefederation",
    imageUrl: "helmets/dp40heroofthefederation.webp",
    tier: "b",
  },
  {
    displayName: "DP-53 Savior of the Free",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond0",
    internalName: "dp53saviorofthefree",
    imageUrl: "helmets/dp53saviorofthefree.webp",
    tier: "b",
  },
  {
    displayName: "EX-03 Prototype 3",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond5",
    internalName: "ex03prototype3",
    imageUrl: "helmets/ex03prototype3.webp",
    tier: "b",
  },
  {
    displayName: "EX-16 Prototype 16",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond5",
    internalName: "ex16prototype16",
    imageUrl: "helmets/ex16prototype16.webp",
    tier: "b",
  },
  {
    displayName: "FS-34 Exterminator",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond1",
    internalName: "fs34exterminator",
    imageUrl: "helmets/fs34exterminator.webp",
    tier: "b",
  },
  {
    displayName: "I-92 Fire Fighter",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond1",
    internalName: "i92firefighter",
    imageUrl: "helmets/i92firefighter.webp",
    tier: "b",
  },
  {
    displayName: "I-102 Draconaught",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond9",
    internalName: "i102draconaught",
    imageUrl: "helmets/i102draconaught.webp",
    tier: "b",
  },
  {
    displayName: "PH-56 Jaguar",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond1",
    internalName: "ph56jaguar",
    imageUrl: "helmets/ph56jaguar.webp",
    tier: "b",
  },
  {
    displayName: "SA-04 Combat Technician",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond3",
    internalName: "sa04combattechnician",
    imageUrl: "helmets/sa04combattechnician.webp",
    tier: "b",
  },
  {
    displayName: "SA-12 Servo Assisted",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond4",
    internalName: "sa12servoassisted",
    imageUrl: "helmets/sa12servoassisted.webp",
    tier: "b",
  },
  {
    displayName: "SA-25 Steel Trooper",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond4",
    internalName: "sa25steeltrooper",
    imageUrl: "helmets/sa25steeltrooper.webp",
    tier: "b",
  },
  {
    displayName: "SA-15 Drone Master",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond1",
    internalName: "sc15dronemaster",
    imageUrl: "helmets/sc15dronemaster.webp",
    tier: "b",
  },
  {
    displayName: "TR-7 Ambassador of the Brand",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond2",
    internalName: "tr7ambassadorofthebrand",
    imageUrl: "helmets/tr7ambassadorofthebrand.webp",
    tier: "b",
  },
  {
    displayName: "TR-9 Cavalier of Democracy",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond2",
    internalName: "tr9cavalierofdemocracy",
    imageUrl: "helmets/tr9cavalierofdemocracy.webp",
    tier: "b",
  },
  {
    displayName: "TR-40 Gold Eagle",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "none",
    internalName: "tr40goldeagle",
    imageUrl: "helmets/tr40goldeagle.webp",
    tier: "b",
  },
  {
    displayName: "TR-117 Alpha Commander",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "none",
    internalName: "tr117alphacommander",
    imageUrl: "helmets/tr117alphacommander.webp",
    tier: "b",
  },
  {
    displayName: "UF-50 Bloodhound",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond11",
    internalName: "uf50bloodhound",
    imageUrl: "helmets/uf50bloodhound.webp",
    tier: "b",
  },
  {
    displayName: "UF-84 Doubt Killer",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond1",
    internalName: "uf84doubtkiller",
    imageUrl: "helmets/uf84doubtkiller.webp",
    tier: "b",
  },
  {
    displayName: "AF-52 Lockdown",
    type: "Equipment",
    category: "helmet",
    tags: ["Heavy"],
    warbondCode: "warbond1",
    internalName: "af52lockdown",
    imageUrl: "helmets/af52lockdown.webp",
    tier: "b",
  },
  {
    displayName: "B-27 Fortified Commando",
    type: "Equipment",
    category: "helmet",
    tags: ["Heavy"],
    warbondCode: "warbond1",
    internalName: "b27fortifiedcommando",
    imageUrl: "helmets/b27fortifiedcommando.webp",
    tier: "b",
  },
  {
    displayName: "CE-64 Grenadier",
    type: "Equipment",
    category: "helmet",
    tags: ["Heavy"],
    warbondCode: "warbond1",
    internalName: "ce64grenadier",
    imageUrl: "helmets/ce64grenadier.webp",
    tier: "b",
  },
  {
    displayName: "CE-101 Guerilla Gorilla",
    type: "Equipment",
    category: "helmet",
    tags: ["Heavy"],
    warbondCode: "warbond1",
    internalName: "ce101guerillagorilla",
    imageUrl: "helmets/ce101guerillagorilla.webp",
    tier: "b",
  },
  {
    displayName: "CM-17 Butcher",
    type: "Equipment",
    category: "helmet",
    tags: ["Heavy"],
    warbondCode: "warbond1",
    internalName: "cm17butcher",
    imageUrl: "helmets/cm17butcher.webp",
    tier: "b",
  },
  {
    displayName: "CW-22 Kodiak",
    type: "Equipment",
    category: "helmet",
    tags: ["Heavy"],
    warbondCode: "warbond7",
    internalName: "cw22kodiak",
    imageUrl: "helmets/cw22kodiak.webp",
    tier: "b",
  },
  {
    displayName: "CW-36 Winter Warrior",
    type: "Equipment",
    category: "helmet",
    tags: ["Heavy"],
    warbondCode: "warbond7",
    internalName: "cw36winterwarrior",
    imageUrl: "helmets/cw36winterwarrior.webp",
    tier: "b",
  },
  {
    displayName: "FS-05 Marksman",
    type: "Equipment",
    category: "helmet",
    tags: ["Heavy"],
    warbondCode: "warbond3",
    internalName: "fs05marksman",
    imageUrl: "helmets/fs05marksman.webp",
    tier: "b",
  },
  {
    displayName: "FS-11 Executioner",
    type: "Equipment",
    category: "helmet",
    tags: ["Heavy"],
    warbondCode: "warbond1",
    internalName: "fs11executioner",
    imageUrl: "helmets/fs11executioner.webp",
    tier: "b",
  },
  {
    displayName: "FS-23 Battle Master",
    type: "Equipment",
    category: "helmet",
    tags: ["Heavy"],
    warbondCode: "warbond3",
    internalName: "fs23battlemaster",
    imageUrl: "helmets/fs23battlemaster.webp",
    tier: "b",
  },
  {
    displayName: "FS-55 Devastator",
    type: "Equipment",
    category: "helmet",
    tags: ["Heavy"],
    warbondCode: "warbond6",
    internalName: "fs55devastator",
    imageUrl: "helmets/fs55devastator.webp",
    tier: "b",
  },
  {
    displayName: "FS-61 Dreadnought",
    type: "Equipment",
    category: "helmet",
    tags: ["Heavy"],
    warbondCode: "warbond1",
    internalName: "fs61dreadnought",
    imageUrl: "helmets/fs61dreadnought.webp",
    tier: "b",
  },
  {
    displayName: "I-44 Salamander",
    type: "Equipment",
    category: "helmet",
    tags: ["Heavy"],
    warbondCode: "warbond1",
    internalName: "i44salamander",
    imageUrl: "helmets/i44salamander.webp",
    tier: "b",
  },
  {
    displayName: "PH-202 Twigsnapper",
    type: "Equipment",
    category: "helmet",
    tags: ["Heavy"],
    warbondCode: "warbond8",
    internalName: "ph202twigsnapper",
    imageUrl: "helmets/ph202twigsnapper.webp",
    tier: "b",
  },
  {
    displayName: "SA-32 Dynamo",
    type: "Equipment",
    category: "helmet",
    tags: ["Heavy"],
    warbondCode: "warbond4",
    internalName: "sa32dynamo",
    imageUrl: "helmets/sa32dynamo.webp",
    tier: "b",
  },
  {
    displayName: "TR-62 Knight",
    type: "Equipment",
    category: "helmet",
    tags: ["Heavy"],
    warbondCode: "warbond2",
    internalName: "tr62knight",
    imageUrl: "helmets/tr62knight.webp",
    tier: "b",
  },
  {
    displayName: "SR-64 Cinderblock",
    type: "Equipment",
    category: "helmet",
    tags: ["Heavy"],
    warbondCode: "warbond1",
    internalName: "sr64cinderblock",
    imageUrl: "helmets/sr64cinderblock.webp",
    tier: "b",
  },
  {
    displayName: "B-22 Model Citizen",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "none",
    internalName: "b22modelcitizen",
    imageUrl: "helmets/b22modelcitizen.webp",
    tier: "b",
  },
  {
    displayName: "IE-3 Martyr",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond13",
    internalName: "ie3martyr",
    imageUrl: "helmets/ie3martyr.webp",
    tier: "b",
  },
  {
    displayName: "IE-12 Righteous",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond13",
    internalName: "ie12righteous",
    imageUrl: "helmets/ie12righteous.webp",
    tier: "b",
  },
  {
    displayName: "IE-57 Hell-Bent",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond1",
    internalName: "ie57hellbent",
    imageUrl: "helmets/ie57hellbent.webp",
    tier: "b",
  },
  {
    displayName: "GS-17 Frontier Marshal",
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond14",
    internalName: "gs17frontiermarshal",
    imageUrl: "helmets/gs17frontiermarshal.webp",
    tier: "b",
  },
  {
    displayName: "GS-66 Lawmaker",
    type: "Equipment",
    category: "helmet",
    tags: ["Heavy"],
    warbondCode: "warbond14",
    internalName: "gs66lawmaker",
    imageUrl: "helmets/gs66lawmaker.webp",
    tier: "b",
  },
  {
    displayName: `GS-11 Democracy's Deputy`,
    type: "Equipment",
    category: "helmet",
    tags: ["Light"],
    warbondCode: "warbond1",
    internalName: "gs11democracysdeputy",
    imageUrl: "helmets/gs11democracysdeputy.webp",
    tier: "b",
  },
  {
    displayName: `RE-824 Bearer of the Standard`,
    type: "Equipment",
    category: "helmet",
    tags: ["Heavy"],
    warbondCode: "warbond1",
    internalName: "re824bearerofthestandard",
    imageUrl: "helmets/re824bearerofthestandard.webp",
    tier: "b",
  },
  {
    displayName: `RE-1861 Parade Commander`,
    type: "Equipment",
    category: "helmet",
    tags: ["Light"],
    warbondCode: "warbond15",
    internalName: "re1861paradecommander",
    imageUrl: "helmets/re1861paradecommander.webp",
    tier: "b",
  },
  {
    displayName: `RE-2310 Honorary Guard`,
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond15",
    internalName: "re2310honoraryguard",
    imageUrl: "helmets/re2310honoraryguard.webp",
    tier: "b",
  },
  {
    displayName: `BP-20 Correct Officer`,
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond16",
    internalName: "bp20correctofficer",
    imageUrl: "helmets/bp20correctofficer.webp",
    tier: "b",
  },
  {
    displayName: `BP-32 Jackboot`,
    type: "Equipment",
    category: "helmet",
    tags: ["Light"],
    warbondCode: "warbond16",
    internalName: "bp32jackboot",
    imageUrl: "helmets/bp32jackboot.webp",
    tier: "b",
  },
  {
    displayName: `BP-77 Grand Juror`,
    type: "Equipment",
    category: "helmet",
    tags: ["Heavy"],
    warbondCode: "warbond1",
    internalName: "bp77grandjuror",
    imageUrl: "helmets/bp77grandjuror.webp",
    tier: "b",
  },
  {
    displayName: `AD-11 Livewire`,
    type: "Equipment",
    category: "helmet",
    tags: ["Light"],
    warbondCode: "warbond17",
    internalName: "ad11livewire",
    imageUrl: "helmets/ad11livewire.webp",
    tier: "b",
  },
  {
    displayName: `AD-26 Bleeding Edge`,
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond17",
    internalName: "ad26bleedingedge",
    imageUrl: "helmets/ad26bleedingedge.webp",
    tier: "b",
  },
  {
    displayName: `AD-49 Apollonian`,
    type: "Equipment",
    category: "helmet",
    tags: ["Heavy"],
    warbondCode: "warbond17",
    internalName: "ad49apollonian",
    imageUrl: "helmets/ad49apollonian.webp",
    tier: "b",
  },
  {
    displayName: `A-9 Helljumper`,
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond19",
    internalName: "a9helljumper",
    imageUrl: "helmets/a9helljumper.webp",
    tier: "b",
  },
  {
    displayName: `A-35 Recon`,
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond19",
    internalName: "a35recon",
    imageUrl: "helmets/a35recon.webp",
    tier: "b",
  },
  {
    displayName: `DS-42 Federation's Blade`,
    type: "Equipment",
    category: "helmet",
    tags: ["Heavy"],
    warbondCode: "warbond20",
    internalName: "ds42federationsblade",
    imageUrl: "helmets/ds42federationsblade.webp",
    tier: "b",
  },
  {
    displayName: `DS-191 Scorpion`,
    type: "Equipment",
    category: "helmet",
    tags: ["Medium"],
    warbondCode: "warbond20",
    internalName: "ds191scorpion",
    imageUrl: "helmets/ds191scorpion.webp",
    tier: "b",
  },
  {
    displayName: `DS-10 Big Game Hunter`,
    type: "Equipment",
    category: "helmet",
    tags: ["Light"],
    warbondCode: "warbond1",
    internalName: "ds10biggamehunter",
    imageUrl: "helmets/ds10biggamehunter.webp",
    tier: "b",
  },
];
