export function getPrimary(displayName) {
  return PRIMARIES.find((item) => item.displayName === displayName);
}

export const PRIMARIES = [
  {
    displayName: "Liberator",
    type: "Equipment",
    category: "primary",
    tags: ["AssaultRifle"],
    warbondCode: "none",
    internalName: "ar23liberator",
    imageUrl: "equipment/ar23liberator.png",
    tier: "b",
  },
  {
    displayName: "Liberator Penetrator",
    type: "Equipment",
    category: "primary",
    tags: ["AssaultRifle"],
    warbondCode: "warbond3",
    internalName: "ar23pliberatorpenetrator",
    imageUrl: "equipment/ar23pliberatorpenetrator.png",
    tier: "a",
  },
  {
    displayName: "Liberator Concussive",
    type: "Equipment",
    category: "primary",
    tags: ["AssaultRifle"],
    warbondCode: "warbond4",
    internalName: "ar23cliberatorconcussive",
    imageUrl: "equipment/ar23cliberatorconcussive.png",
    tier: "d",
  },
  {
    displayName: "Liberator Carbine",
    type: "Equipment",
    category: "primary",
    tags: ["AssaultRifle"],
    warbondCode: "warbond8",
    internalName: "ar23aliberatorcarbine",
    imageUrl: "equipment/ar23aliberatorcarbine.png",
    tier: "c",
  },
  {
    displayName: "Adjudicator",
    type: "Equipment",
    category: "primary",
    tags: ["AssaultRifle"],
    warbondCode: "warbond6",
    internalName: "br14adjudicator",
    imageUrl: "equipment/br14adjudicator.png",
    tier: "a",
  },
  {
    displayName: "StA-52 Assault Rifle",
    type: "Equipment",
    category: "primary",
    tags: ["AssaultRifle"],
    warbondCode: "warbond18",
    internalName: "sta52assaultrifle",
    imageUrl: "equipment/sta52assaultrifle.png",
    tier: "c",
  },
  {
    displayName: "Pacifier",
    type: "Equipment",
    category: "primary",
    tags: ["AssaultRifle"],
    warbondCode: "warbond16",
    internalName: "ar32pacifier",
    imageUrl: "equipment/ar32pacifier.png",
    tier: "c",
  },
  {
    displayName: "Tenderizer",
    type: "Equipment",
    category: "primary",
    tags: ["AssaultRifle"],
    warbondCode: "warbond7",
    internalName: "ar61tenderizer",
    imageUrl: "equipment/ar61tenderizer.png",
    tier: "c",
  },
  {
    displayName: "MA5C Assault Rifle",
    type: "Equipment",
    category: "primary",
    tags: ["AssaultRifle"],
    warbondCode: "warbond19",
    internalName: "ma5c",
    imageUrl: "equipment/ma5c.png",
    tier: "b",
  },
  {
    displayName: "AR-2 Coyote",
    type: "Equipment",
    category: "primary",
    tags: ["AssaultRifle"],
    warbondCode: "warbond20",
    internalName: "ar2coyote",
    imageUrl: "equipment/ar2coyote.png",
    tier: "a",
  },
  {
    displayName: "Variable",
    type: "Equipment",
    category: "primary",
    tags: ["AssaultRifle"],
    warbondCode: "warbond17",
    internalName: "variable",
    imageUrl: "equipment/variable.png",
    tier: "a",
  },
  {
    displayName: "Defender",
    type: "Equipment",
    category: "primary",
    tags: ["SubmachineGun"],
    warbondCode: "warbond3",
    internalName: "smg37defender",
    imageUrl: "equipment/smg37defender.png",
    tier: "c",
  },
  {
    displayName: "Pummeler",
    type: "Equipment",
    category: "primary",
    tags: ["SubmachineGun"],
    warbondCode: "warbond7",
    internalName: "smg72pummeler",
    imageUrl: "equipment/smg72pummeler.png",
    tier: "c",
  },
  {
    displayName: "Reprimand",
    type: "Equipment",
    category: "primary",
    tags: ["Submachinegun"],
    warbondCode: "warbond11",
    internalName: "smg32reprimand",
    imageUrl: "equipment/smg32reprimand.png",
    tier: "a",
  },
  {
    displayName: "StA-11 SMG",
    type: "Equipment",
    category: "primary",
    tags: ["Submachinegun"],
    warbondCode: "warbond18",
    internalName: "sta11smg",
    imageUrl: "equipment/sta11smg.png",
    tier: "b",
  },
  {
    displayName: "Knight",
    type: "Equipment",
    category: "primary",
    tags: ["SubmachineGun"],
    warbondCode: "warbond0",
    internalName: "mp98knight",
    imageUrl: "equipment/mp98knight.png",
    tier: "b",
  },
  {
    displayName: "M7S SMG",
    type: "Equipment",
    category: "primary",
    tags: ["SubmachineGun"],
    warbondCode: "warbond19",
    internalName: "m7s",
    imageUrl: "equipment/m7s.png",
    tier: "c",
  },
  {
    displayName: "Punisher",
    type: "Equipment",
    category: "primary",
    tags: ["Shotgun"],
    warbondCode: "warbond3",
    internalName: "sg8punisher",
    imageUrl: "equipment/sg8punisher.png",
    tier: "c",
  },
  {
    displayName: "Cookout",
    type: "Equipment",
    category: "primary",
    tags: ["Shotgun"],
    warbondCode: "warbond9",
    internalName: "sg451cookout",
    imageUrl: "equipment/sg451cookout.png",
    tier: "a",
  },
  {
    displayName: "Slugger",
    type: "Equipment",
    category: "primary",
    tags: ["Shotgun"],
    warbondCode: "warbond3",
    internalName: "sg8sslugger",
    imageUrl: "equipment/sg8sslugger.png",
    tier: "b",
  },
  {
    displayName: "Breaker",
    type: "Equipment",
    category: "primary",
    tags: ["Shotgun"],
    warbondCode: "warbond3",
    internalName: "sg225breaker",
    imageUrl: "equipment/sg225breaker.png",
    tier: "c",
  },
  {
    displayName: "Breaker Incendiary",
    type: "Equipment",
    category: "primary",
    tags: ["Shotgun"],
    warbondCode: "warbond4",
    internalName: "sg225iebreakerincendiary",
    imageUrl: "equipment/sg225iebreakerincendiary.png",
    tier: "b",
  },
  {
    displayName: "Breaker Spray & Pray",
    type: "Equipment",
    category: "primary",
    tags: ["Shotgun"],
    warbondCode: "warbond3",
    internalName: "sg225spbreakerspraynpray",
    imageUrl: "equipment/sg225spbreakerspraynpray.png",
    tier: "a",
  },
  {
    displayName: "Halt",
    type: "Equipment",
    category: "primary",
    tags: ["Shotgun"],
    warbondCode: "warbond11",
    internalName: "sg20halt",
    imageUrl: "equipment/sg20halt.png",
    tier: "b",
  },
  {
    displayName: "M90A Shotgun",
    type: "Equipment",
    category: "primary",
    tags: ["Shotgun"],
    warbondCode: "warbond19",
    internalName: "m90a",
    imageUrl: "equipment/m90a.png",
    tier: "c",
  },
  {
    displayName: "Diligence",
    type: "Equipment",
    category: "primary",
    tags: ["MarksmanRifle"],
    warbondCode: "warbond3",
    internalName: "r63diligence",
    imageUrl: "equipment/r63diligence.png",
    tier: "b",
  },
  {
    displayName: "Diligence Counter Sniper",
    type: "Equipment",
    category: "primary",
    tags: ["MarksmanRifle"],
    warbondCode: "warbond3",
    internalName: "r63csdiligencecountersniper",
    imageUrl: "equipment/r63csdiligencecountersniper.png",
    tier: "s",
  },
  {
    displayName: "Deadeye",
    type: "Equipment",
    category: "primary",
    tags: ["MarksmanRifle"],
    warbondCode: "warbond14",
    internalName: "r6deadeye",
    imageUrl: "equipment/r6deadeye.png",
    tier: "b",
  },
  {
    displayName: "Amendment",
    type: "Equipment",
    category: "primary",
    tags: ["MarksmanRifle"],
    warbondCode: "warbond15",
    internalName: "r2amendment",
    imageUrl: "equipment/r2amendment.png",
    tier: "c",
  },
  {
    displayName: "Constitution",
    type: "Equipment",
    category: "primary",
    tags: ["MarksmanRifle"],
    warbondCode: "none",
    internalName: "r2124constitution",
    imageUrl: "equipment/r2124constitution.png",
    tier: "d",
    overrideCost: 1,
  },
  {
    displayName: "Scythe",
    type: "Equipment",
    category: "primary",
    tags: ["EnergyWeapon"],
    warbondCode: "warbond3",
    internalName: "las5scythe",
    imageUrl: "equipment/las5scythe.png",
    tier: "c",
  },
  {
    displayName: "Sickle",
    type: "Equipment",
    category: "primary",
    tags: ["EnergyWeapon"],
    warbondCode: "warbond5",
    internalName: "las16sickle",
    imageUrl: "equipment/las16sickle.png",
    tier: "b",
  },
  {
    displayName: "Scorcher",
    type: "Equipment",
    category: "primary",
    tags: ["EnergyWeapon"],
    warbondCode: "warbond3",
    internalName: "plas1scorcher",
    imageUrl: "equipment/plas1scorcher.png",
    tier: "b",
  },
  {
    displayName: "Purifier",
    type: "Equipment",
    category: "primary",
    tags: ["EnergyWeapon"],
    warbondCode: "warbond7",
    internalName: "plas101purifier",
    imageUrl: "equipment/plas101purifier.png",
    tier: "a",
  },
  {
    displayName: "Punisher Plasma",
    type: "Equipment",
    category: "primary",
    tags: ["EnergyWeapon"],
    warbondCode: "warbond5",
    internalName: "sg8ppunisherplasma",
    imageUrl: "equipment/sg8ppunisherplasma.png",
    tier: "c",
  },
  {
    displayName: "Blitzer",
    type: "Equipment",
    category: "primary",
    tags: ["EnergyWeapon"],
    warbondCode: "warbond5",
    internalName: "arc12blitzer",
    imageUrl: "equipment/arc12blitzer.png",
    tier: "c",
  },
  {
    displayName: "Double Edge Sickle",
    type: "Equipment",
    category: "primary",
    tags: ["EnergyWeapon"],
    warbondCode: "warbond13",
    internalName: "las17doubleedgesickle",
    imageUrl: "equipment/las17doubleedgesickle.png",
    tier: "a",
  },
  {
    displayName: "PLAS-39 Accelerator Rifle",
    type: "Equipment",
    category: "primary",
    tags: ["MarksmanRifle"],
    warbondCode: "none",
    internalName: "plas39acceleratorrifle",
    imageUrl: "equipment/plas39acceleratorrifle.png",
    tier: "d",
  },
  {
    displayName: "Eruptor",
    type: "Equipment",
    category: "primary",
    tags: ["Explosive"],
    warbondCode: "warbond6",
    internalName: "r36eruptor",
    imageUrl: "equipment/r36eruptor.png",
    tier: "s",
  },
  {
    displayName: "Exploding Crossbow",
    type: "Equipment",
    category: "primary",
    tags: ["Explosive"],
    warbondCode: "warbond6",
    internalName: "cb9explodingcrossbow",
    imageUrl: "equipment/cb9explodingcrossbow.png",
    tier: "s",
  },
  {
    displayName: "Dominator",
    type: "Equipment",
    category: "primary",
    tags: ["Explosive"],
    warbondCode: "warbond4",
    internalName: "jar5dominator",
    imageUrl: "equipment/jar5dominator.png",
    tier: "b",
  },
  {
    displayName: "Torcher",
    type: "Equipment",
    category: "primary",
    tags: ["Special"],
    warbondCode: "warbond9",
    internalName: "flam66torcher",
    imageUrl: "equipment/flam66torcher.png",
    tier: "c",
  },
];
