export const QUESTS = [
  {
    displayName: "Collect at least X samples",
    description: "Collect samples so our researchers can keep inventing things that explode harder, better, and more democratically.",
    type: "objective",
    category: "mobility",
    values: [25, 37, 50, 62, 75],
    rewards: [20, 27, 35, 42, 50],
  },
  {
    displayName: "Cover at least X km",
    description: "Every meter walked is another stomp on the face of tyranny.",
    type: "objective",
    category: "mobility",
    datatype: "float",
    tags: ["exclusivetravel"],
    values: [4, 5.5, 7, 8.5, 10],
    rewards: [20, 27, 35, 42, 50],
  },
  {
    displayName: "Extract with at least X% time remaining",
    description: "Efficiency is the bedrock of democracy. Finish early so you can liberate even more tomorrow!",
    type: "objective",
    category: "mobility",
    values: [15, 24, 32, 41, 50],
    rewards: [20, 27, 35, 42, 50],
  },
  {
    displayName: "Cover at most X km",
    description: "Hold the line, and let freedom come to you. Remember: Movement is for cowards and xenos scum.",
    type: "objective",
    category: "mobility",
    datatype: "float",
    tags: ["exclusivetravel"],
    values: [7, 6.25, 5.5, 4.75, 4],
    rewards: [20, 27, 35, 42, 50],
  },
  {
    displayName: "Secure at least X kills",
    description: "Stack bodies high for liberty! The more corpses you leave behind, the closer we get to peace.",
    type: "objective",
    category: "lethality",
    tags: ["exclisivekills"],
    values: [250, 362, 475, 587, 700],
    rewards: [20, 27, 35, 42, 50],
  },
  {
    displayName: "Secure at least X melee kills",
    description: "Show the enemy that Super Earth’s handshake comes with a closed fist.",
    type: "objective",
    category: "lethality",
    tags: ["exclisivekills"],
    values: [10, 32, 55, 77, 100],
    rewards: [20, 27, 35, 42, 50],
  },
  {
    displayName: "Achieve at least X% weapon accuracy",
    description: "Precision is the difference between a hero and a court-martial.",
    type: "objective",
    category: "lethality",
    values: [50, 61, 73, 84, 95],
    rewards: [20, 27, 35, 42, 50],
  },
  {
    displayName: "Call in at least X stratagems",
    description: "The skies are ours. Rain down freedom like it's a thunderstorm of democracy.",
    type: "objective",
    category: "lethality",
    tags: ["exclisivestratagems"],
    values: [25, 29, 32, 36, 40],
    rewards: [20, 27, 35, 42, 50],
  },
  {
    displayName: "Fire at least X rounds",
    description: "If it moves, shoots it. If it doesn't move, shoot it anyway just to be sure.",
    type: "objective",
    category: "lethality",
    tags: ["exclisiveammunition"],
    values: [500, 1000, 1500, 2000, 2500],
    rewards: [20, 27, 35, 42, 50],
  },
  {
    displayName: "Die at most X times",
    description: "Try not to die. Dying is unpatriotic, and basic training isn't cheap.",
    type: "objective",
    category: "survivability",
    values: [8, 6, 5, 3, 1],
    rewards: [20, 27, 35, 42, 50],
  },
  {
    displayName: "Maintain a K:D of X:1",
    description: "Super Earth invested in your training. Make it a profitable return.",
    type: "objective",
    category: "survivability",
    values: [60, 107, 155, 202, 250],
    rewards: [20, 27, 35, 42, 50],
  },
  {
    displayName: "Stim at most X times",
    description: "Pain is weakness leaving the body. Or entering it. Either way, walk it off, helldiver.",
    type: "objective",
    category: "survivability",
    values: [25, 20, 15, 10, 5],
    rewards: [20, 27, 35, 42, 50],
  },
  {
    displayName: "Be responsible for at most X accidentals",
    description: "Friendly fire isn't actually friendly.",
    type: "objective",
    category: "survivability",
    values: [2, 2, 1, 1, 0],
    rewards: [20, 27, 35, 42, 50],
  },
  {
    displayName: "Secure at most X kills",
    description: "This is a targeted operation, not a buffet. Control your enthusiasm.",
    type: "objective",
    category: "stealth",
    tags: ["exclisivekills"],
    values: [200, 163, 125, 88, 50],
    rewards: [20, 27, 35, 42, 50],
  },
  {
    displayName: "Call in at most X stratagems",
    description: "Minimal fire support requested. Command is testing something. Don't ask.",
    type: "objective",
    category: "stealth",
    tags: ["exclisivestratagems"],
    values: [30, 25, 20, 15, 10],
    rewards: [20, 27, 35, 42, 50],
  },
  {
    displayName: "Fire at most X rounds",
    description: "High Command is reviewing fleet ammo expenses. Again.",
    type: "objective",
    category: "stealth",
    tags: ["exclisiveammunition"],
    values: [300, 244, 187, 131, 75],
    rewards: [20, 27, 35, 42, 50],
  },
  {
    displayName: "Allow enemy reinforcements at most X times",
    description: "If we wanted a full-on war, we'd throw a thousand SEAF troopers at the problem.",
    type: "objective",
    category: "stealth",
    tags: ["exclisivekills"],
    values: [25, 20, 15, 10, 5],
    rewards: [20, 27, 35, 42, 50],
  },
];
