export function getSecondary(displayName) {
  return SECONDARIES.find((item) => item.displayName === displayName);
}

export const SECONDARIES = [
  {
    displayName: "Peacemaker",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "none",
    internalName: "p2peacemaker",
    imageUrl: "equipment/p2peacemaker.png",
    tier: "c",
  },
  {
    displayName: "Combat Hatchet",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond1",
    internalName: "cqc5combathatchet",
    imageUrl: "equipment/cqc5combathatchet.png",
    tier: "d",
  },
  {
    displayName: "Saber",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond15",
    internalName: "cqc2saber",
    imageUrl: "equipment/cqc2saber.png",
    tier: "d",
  },
  {
    displayName: "Machete",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond1",
    internalName: "cqc42machete",
    imageUrl: "equipment/cqc42machete.png",
    tier: "d",
  },
  {
    displayName: "Stun Lance",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond12",
    internalName: "cqc19stunlance",
    imageUrl: "equipment/cqc19stunlance.png",
    tier: "d",
  },
  {
    displayName: "Stun Baton",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond1",
    internalName: "cqc30stunbaton",
    imageUrl: "equipment/cqc30stunbaton.png",
    tier: "d",
  },
  {
    displayName: "Stim Pistol",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond10",
    internalName: "p11stimpistol",
    imageUrl: "equipment/p11stimpistol.png",
    tier: "d",
  },
  {
    displayName: "Loyalist",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond11",
    internalName: "plas15loyalist",
    imageUrl: "equipment/plas15loyalist.png",
    tier: "b",
  },
  {
    displayName: "Bushwhacker",
    type: "Equipment",
    category: "secondary",
    tags: ["Shotgun"],
    warbondCode: "warbond8",
    internalName: "sg22bushwhacker",
    imageUrl: "equipment/sg22bushwhacker.png",
    tier: "b",
  },
  {
    displayName: "Redeemer",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond3",
    internalName: "p19redeemer",
    imageUrl: "equipment/p19redeemer.png",
    tier: "b",
  },
  {
    displayName: "Grenade Pistol",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond6",
    internalName: "gp31grenadepistol",
    imageUrl: "equipment/gp31grenadepistol.png",
    tier: "a",
  },
  {
    displayName: "Verdict",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond7",
    internalName: "p113verdict",
    imageUrl: "equipment/p113verdict.png",
    tier: "a",
  },
  {
    displayName: "Senator",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond4",
    internalName: "p4senator",
    imageUrl: "equipment/p4senator.png",
    tier: "a",
  },
  {
    displayName: "Dagger",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond5",
    internalName: "las7dagger",
    imageUrl: "equipment/las7dagger.png",
    tier: "c",
  },
  {
    displayName: "Talon",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond14",
    internalName: "las58talon",
    imageUrl: "equipment/las58talon.png",
    tier: "a",
  },
  {
    displayName: "Crisper",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond9",
    internalName: "p72crisper",
    imageUrl: "equipment/p72crisper.png",
    tier: "b",
  },
  {
    displayName: "GP-31 Ultimatum",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond13",
    internalName: "gp31ultimatum",
    imageUrl: "equipment/gp31ultimatum.png",
    tier: "s",
  },
  {
    displayName: "P-92 Warrant",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond1",
    internalName: "p92warrant",
    imageUrl: "equipment/p92warrant.png",
    tier: "b",
  },

  {
    displayName: "M6C/SOCOM",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond19",
    internalName: "m6csocompistol",
    imageUrl: "equipment/m6csocompistol.png",
    tier: "b",
  },
];
