export function getSecondary(displayName) {
  return SECONDARIES.find((item) => item.displayName === displayName);
}

export const SECONDARIES = [
  {
    displayName: 'P-2 Peacemaker',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'none',
    internalName: 'p2peacemaker',
    imageUrl: 'equipment/p2peacemaker.png',
    tier: 'c',
    wikiSlug: 'P-2_Peacemaker',
    hoverTexts: [
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-weapon">\n<tbody><tr>\n<th colspan="2">P-2 Peacemaker\n</th></tr>\n<tr>\n<td>Fire Rate</td>\n<td>900 rpm\n</td></tr>\n<tr>\n<td>Recoil</td>\n<td>23\n</td></tr>\n<tr>\n<td>Sway</td>\n<td>1.2\n</td></tr>\n<tr>\n<td>Ergonomics</td>\n<td>100\n</td></tr>\n<tr>\n<td>Capacity</td>\n<td>15\n</td></tr>\n<tr>\n<td>Reload Time</td>\n<td>1.8  s\n</td></tr>\n<tr>\n<td>Tactical Reload</td>\n<td>1.4 s\n</td></tr>\n<tr>\n<td>Spare Magazines</td>\n<td>8\n</td></tr>\n<tr>\n<td>Starting Magazines</td>\n<td>5\n</td></tr>\n<tr>\n<td>Mags from Supply</td>\n<td>6\n</td></tr>\n<tr>\n<td>Mags from Ammo Box</td>\n<td>3\n</td></tr>\n<tr>\n<th colspan="2">Attacks\n</th></tr>\n<tr>\n<td>Pistol 9x20mm Hollow-Point</td>\n<td>Projectile\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-projectile">\n<tbody><tr>\n<th colspan="2">Pistol 9x20mm Hollow-Point\n</th></tr>\n<tr>\n<th colspan="2">Projectile\n</th></tr>\n<tr>\n<td>Caliber</td>\n<td>9 mm\n</td></tr>\n<tr>\n<td>Mass</td>\n<td>7 g\n</td></tr>\n<tr>\n<td>Initial Velocity</td>\n<td>320 m/s\n</td></tr>\n<tr>\n<td>Drag Factor</td>\n<td>60%\n</td></tr>\n<tr>\n<td>Gravity Factor</td>\n<td>100%\n</td></tr>\n<tr>\n<td>Penetration Slowdown</td>\n<td>25%\n</td></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Standard</td>\n<td><a title="Damage"></a>85 Damage\n</td></tr>\n<tr>\n<td>vs. Durable</td>\n<td><a title="Damage"></a>25 Damage\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Direct</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Light</a></span>\n</td></tr>\n<tr>\n<td>Slight Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Light</a></span>\n</td></tr>\n<tr>\n<td>Large Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Light</a></span>\n</td></tr>\n<tr>\n<td>Extreme Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<th colspan="2">Special Effects\n</th></tr>\n<tr>\n<td>Demolition Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>4\n</td></tr>\n</tbody></table>'
    ]
  },
  {
    displayName: 'CQC-5 Combat Hatchet',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond1',
    internalName: 'cqc5combathatchet',
    imageUrl: 'equipment/cqc5combathatchet.png',
    tier: 'd',
    overrideCost: 1,
    wikiSlug: 'CQC-5_Combat_Hatchet',
    hoverTexts: [
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-weapon">\n<tbody><tr>\n<th colspan="2">CQC-5 Combat Hatchet\n</th></tr>\n<tr>\n<td>Fire Rate</td>\n<td>150 rpm\n</td></tr>\n<tr>\n<td>Recoil</td>\n<td>0\n</td></tr>\n<tr>\n<td>Ergonomics</td>\n<td>0\n</td></tr>\n<tr>\n<th colspan="2">Attacks\n</th></tr>\n<tr>\n<td>Combat Hatchet</td>\n<td>Damage\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-damage">\n<tbody><tr>\n<th colspan="2">Combat Hatchet\n</th></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Standard</td>\n<td><a title="Damage"></a>110 Damage\n</td></tr>\n<tr>\n<td>vs. Durable</td>\n<td><a title="Damage"></a>55 Damage\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Direct</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Slight Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<td>Large Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<td>Extreme Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<th colspan="2">Special Effects\n</th></tr>\n<tr>\n<td>Demolition Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>25\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>30\n</td></tr>\n</tbody></table>'
    ]
  },
  {
    displayName: 'CQC-2 Saber',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond15',
    internalName: 'cqc2saber',
    imageUrl: 'equipment/cqc2saber.png',
    tier: 'd',
    wikiSlug: 'CQC-2_Saber',
    hoverTexts: [
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-weapon" data-parent="first">\n<tbody><tr>\n<th colspan="2">CQC-2 SABER\n</th></tr>\n<tr>\n<td>Fire Rate</td>\n<td>150  rpm\n</td></tr>\n<tr>\n<td>Ergonomics</td>\n<td>0\n</td></tr>\n<tr>\n<th colspan="2">Attacks\n</th></tr>\n<tr>\n<td><span class="remote-trigger" data-target="CQC-2_M"><span class="remote-text">CQC-2_M</span></span></td>\n<td>Melee\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-melee" id="CQC-2_M">\n<tbody><tr>\n<th colspan="2">CQC-2_M\n</th></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Standard</td>\n<td><a title="Damage"></a>110 Damage\n</td></tr>\n<tr>\n<td>vs. Durable</td>\n<td><a title="Damage"></a>55 Damage\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Direct</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Slight Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<td>Large Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<td>Extreme Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<th colspan="2">Special Effects\n</th></tr>\n<tr>\n<td>Demolition Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>25\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>30\n</td></tr>\n</tbody></table>'
    ]
  },
  {
    displayName: 'CQC-42 Machete',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond1',
    internalName: 'cqc42machete',
    imageUrl: 'equipment/cqc42machete.png',
    tier: 'd',
    wikiSlug: 'CQC-42_Machete',
    hoverTexts: [
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-weapon">\n<tbody><tr>\n<th colspan="2">CQC-42 Machete\n</th></tr>\n<tr>\n<td>Recoil</td>\n<td>0\n</td></tr>\n<tr>\n<td>Ergonomics</td>\n<td>0\n</td></tr>\n<tr>\n<th colspan="2">Attacks\n</th></tr>\n<tr>\n<td>Machete</td>\n<td>Damage\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-damage">\n<tbody><tr>\n<th colspan="2">Machete\n</th></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Standard</td>\n<td><a title="Damage"></a>170 Damage\n</td></tr>\n<tr>\n<td>vs. Durable</td>\n<td><a title="Damage"></a>80 Damage\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Direct</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Slight Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<td>Large Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<td>Extreme Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<th colspan="2">Special Effects\n</th></tr>\n<tr>\n<td>Demolition Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>30\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>10\n</td></tr>\n</tbody></table>'
    ]
  },
  {
    displayName: 'CQC-19 Stun Lance',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond12',
    internalName: 'cqc19stunlance',
    imageUrl: 'equipment/cqc19stunlance.png',
    tier: 'd',
    wikiSlug: 'CQC-19_Stun_Lance',
    hoverTexts: [
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-weapon">\n<tbody><tr>\n<th colspan="2">CQC-19 Stun Lance\n</th></tr>\n<tr>\n<td>Fire Rate</td>\n<td>117 rpm\n</td></tr>\n<tr>\n<td>Recoil</td>\n<td>0\n</td></tr>\n<tr>\n<td>Ergonomics</td>\n<td>0\n</td></tr>\n<tr>\n<th colspan="2">Attacks\n</th></tr>\n<tr>\n<td>Stun Lance</td>\n<td>Damage\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-damage">\n<tbody><tr>\n<th colspan="2">Stun Lance\n</th></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Standard</td>\n<td><a title="Damage"></a>110 Damage\n</td></tr>\n<tr>\n<td>vs. Durable</td>\n<td><a title="Damage"></a>55 Damage\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Direct</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Slight Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<td>Large Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<td>Extreme Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<th colspan="2">Special Effects\n</th></tr>\n<tr>\n<td>Status</td>\n<td><a title="Status Effects">Stun Large</a>\n</td></tr>\n<tr>\n<td>Status Strength</td>\n<td>5\n</td></tr>\n<tr>\n<td>Demolition Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>35\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>30\n</td></tr>\n</tbody></table>'
    ]
  },
  {
    displayName: 'CQC-30 Stun Baton',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond1',
    internalName: 'cqc30stunbaton',
    imageUrl: 'equipment/cqc30stunbaton.png',
    tier: 'd',
    wikiSlug: 'CQC-30_Stun_Baton',
    hoverTexts: [
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-weapon">\n<tbody><tr>\n<th colspan="2">CQC-30 Stun Baton\n</th></tr>\n<tr>\n<td>Fire Rate</td>\n<td>150 rpm\n</td></tr>\n<tr>\n<td>Recoil</td>\n<td>0\n</td></tr>\n<tr>\n<td>Ergonomics</td>\n<td>0\n</td></tr>\n<tr>\n<th colspan="2">Attacks\n</th></tr>\n<tr>\n<td>Stun Baton</td>\n<td>Damage\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-damage">\n<tbody><tr>\n<th colspan="2">Stun Baton\n</th></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Standard</td>\n<td><a title="Damage"></a>50 Damage\n</td></tr>\n<tr>\n<td>vs. Durable</td>\n<td><a title="Damage"></a>25 Damage\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Direct</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Slight Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<td>Large Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<td>Extreme Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<th colspan="2">Special Effects\n</th></tr>\n<tr>\n<td>Status</td>\n<td><a title="Status Effects">Stun Large</a>\n</td></tr>\n<tr>\n<td>Status Strength</td>\n<td>5\n</td></tr>\n<tr>\n<td>Demolition Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>35\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>30\n</td></tr>\n</tbody></table>'
    ]
  },
  {
    displayName: 'P-11 Stim Pistol',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond10',
    internalName: 'p11stimpistol',
    imageUrl: 'equipment/p11stimpistol.png',
    tier: 'd',
    wikiSlug: 'P-11_Stim_Pistol',
    hoverTexts: [
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-weapon">\n<tbody><tr>\n<th colspan="2">P-11 Stim Pistol\n</th></tr>\n<tr>\n<td>Fire Rate</td>\n<td>70 rpm\n</td></tr>\n<tr>\n<td>Sway</td>\n<td>1.2\n</td></tr>\n<tr>\n<td>Ergonomics</td>\n<td>100\n</td></tr>\n<tr>\n<td>Capacity</td>\n<td>6\n</td></tr>\n<tr>\n<td>Spare Rounds</td>\n<td>24\n</td></tr>\n<tr>\n<td>Starting Rounds</td>\n<td>18\n</td></tr>\n<tr>\n<td>Rounds from Supply</td>\n<td>18\n</td></tr>\n<tr>\n<td>Rounds from Ammo Box</td>\n<td>9\n</td></tr>\n<tr>\n<th colspan="2">Attacks\n</th></tr>\n<tr>\n<td>Pistol Stim</td>\n<td>Projectile\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-projectile">\n<tbody><tr>\n<th colspan="2">Pistol Stim\n</th></tr>\n<tr>\n<th colspan="2">Projectile\n</th></tr>\n<tr>\n<td>Caliber</td>\n<td>1 mm\n</td></tr>\n<tr>\n<td>Mass</td>\n<td>1 g\n</td></tr>\n<tr>\n<td>Initial Velocity</td>\n<td>200 m/s\n</td></tr>\n<tr>\n<td>Drag Factor</td>\n<td>10%\n</td></tr>\n<tr>\n<td>Gravity Factor</td>\n<td>100%\n</td></tr>\n<tr>\n<td>Penetration Slowdown</td>\n<td>100%\n</td></tr>\n</tbody></table>'
    ]
  },
  {
    displayName: 'PLAS-15 Loyalist',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond11',
    internalName: 'plas15loyalist',
    imageUrl: 'equipment/plas15loyalist.png',
    tier: 'b',
    wikiSlug: 'PLAS-15_Loyalist',
    hoverTexts: [
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-weapon" data-parent="first">\n<tbody><tr>\n<th colspan="2">PLAS-15 LOYALIST\n</th></tr>\n<tr>\n<td>Fire Rate</td>\n<td>1000  rpm\n</td></tr>\n<tr>\n<td>Recoil</td>\n<td>6.25\n</td></tr>\n<tr>\n<td>Horizontal Recoil</td>\n<td>2.5\n</td></tr>\n<tr>\n<td>Vertical Recoil</td>\n<td>10\n</td></tr>\n<tr>\n<td>Spread</td>\n<td>↔[10.00]  ↕[10.00]\n</td></tr>\n<tr>\n<td>Sway</td>\n<td>1.2\n</td></tr>\n<tr>\n<td>Ergonomics</td>\n<td>95\n</td></tr>\n<tr>\n<td>Capacity</td>\n<td>7\n</td></tr>\n<tr>\n<td>Spare Magazines</td>\n<td>5\n</td></tr>\n<tr>\n<td>Starting Magazines</td>\n<td>3\n</td></tr>\n<tr>\n<td>Mags from Supply</td>\n<td>5\n</td></tr>\n<tr>\n<td>Mags from Ammo Box</td>\n<td>2\n</td></tr>\n<tr>\n<th colspan="2">Charge\n</th></tr>\n<tr>\n<td>at (0.01)s</td>\n<td><span class="remote-trigger" data-target="SMALL_PLASMA_BOLT_P1"><span class="remote-text">SMALL PLASMA BOLT_P1</span></span>× 0.50 dmg\n</td></tr>\n<tr>\n<td>at (1.00)s</td>\n<td><span class="remote-trigger" data-target="SMALL_PLASMA_BOLT_P2"><span class="remote-text">SMALL PLASMA BOLT_P2</span></span>× 0.67 dmg\n</td></tr>\n<tr>\n<td>at (3.00)s</td>\n<td><span class="remote-trigger" data-target="SMALL_PLASMA_BOLT_P2"><span class="remote-text">SMALL PLASMA BOLT_P2</span></span>× 1.00 dmg\n</td></tr>\n<tr>\n<td>Speed Mult Range</td>\n<td>(1.00) (1.00)\n</td></tr>\n<tr>\n<td>Distance Mult Range</td>\n<td>(0.70) (1.40)\n</td></tr>\n<tr>\n<td>Damage Mult Range</td>\n<td>(0.50) (1.00)\n</td></tr>\n<tr>\n<th colspan="2">Attacks\n</th></tr>\n<tr>\n<td>*<span class="remote-trigger" data-target="SMALL_PLASMA_BOLT_P"><span class="remote-text">SMALL PLASMA BOLT P</span></span></td>\n<td>Projectile\n</td></tr>\n<tr>\n<td>*<span class="remote-trigger" data-target="SMALL_PLASMA_BOLT_P1"><span class="remote-text">SMALL PLASMA BOLT P1</span></span></td>\n<td>Projectile\n</td></tr>\n<tr>\n<td>*<span class="remote-trigger" data-target="SMALL_PLASMA_BOLT_P2"><span class="remote-text">SMALL PLASMA BOLT P2</span></span></td>\n<td>Projectile\n</td></tr>\n<tr>\n<td>**<span class="remote-trigger" data-target="SMALL_PLASMA_BOLT_P1_IE"><span class="remote-text">SMALL PLASMA BOLT P1 IE</span></span></td>\n<td>Explosion\n</td></tr>\n<tr>\n<td>**<span class="remote-trigger" data-target="SMALL_PLASMA_BOLT_P2_IE"><span class="remote-text">SMALL PLASMA BOLT P2 IE</span></span></td>\n<td>Explosion\n</td></tr>\n<tr>\n<td>**<span class="remote-trigger" data-target="SMALL_PLASMA_BOLT_P_IE"><span class="remote-text">SMALL PLASMA BOLT P IE</span></span></td>\n<td>Explosion\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-projectile" id="SMALL_PLASMA_BOLT_P">\n<tbody><tr>\n<th colspan="2">SMALL PLASMA BOLT P\n</th></tr>\n<tr>\n<th colspan="2">Projectile\n</th></tr>\n<tr>\n<td>Caliber</td>\n<td>10 mm\n</td></tr>\n<tr>\n<td>Mass</td>\n<td>10 g\n</td></tr>\n<tr>\n<td>Initial Velocity</td>\n<td>550 m/s\n</td></tr>\n<tr>\n<td>Drag Factor</td>\n<td>100%\n</td></tr>\n<tr>\n<td>Gravity Factor</td>\n<td>50%\n</td></tr>\n<tr>\n<td>Penetration Slowdown</td>\n<td>35%\n</td></tr>\n<tr>\n<td>Explosion On Impact</td>\n<td><span class="remote-trigger" data-target="SMALL_PLASMA_BOLT_P_IE"><span class="remote-text">SMALL PLASMA BOLT_P_IE</span></span>\n</td></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Standard</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: default;">100 Ballistic</span></a>\n</td></tr>\n<tr>\n<td>vs. Durable</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: default;">50 Ballistic</span></a>\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Direct</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Light</a></span>\n</td></tr>\n<tr>\n<td>Slight Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Light</a></span>\n</td></tr>\n<tr>\n<td>Large Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Light</a></span>\n</td></tr>\n<tr>\n<td>Extreme Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<th colspan="2">Special Effects\n</th></tr>\n<tr>\n<td>Demolition Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>20\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>10\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-explosion" id="SMALL_PLASMA_BOLT_P_IE">\n<tbody><tr>\n<th colspan="2">SMALL PLASMA BOLT P IE\n</th></tr>\n<tr>\n<th colspan="2">Area of Effect\n</th></tr>\n<tr>\n<td>Inner Radius</td>\n<td>0.75 m\n</td></tr>\n<tr>\n<td>Outer Radius</td>\n<td>1.5 m\n</td></tr>\n<tr>\n<td>Shockwave Radius</td>\n<td>2 m\n</td></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Damage Element</td>\n<td>None\n</td></tr>\n<tr>\n<td>Inner Radius</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: orange;">25 Explosion</span></a>\n</td></tr>\n<tr>\n<td>Inner Durable</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: orange;">25 Explosion</span></a>\n</td></tr>\n<tr>\n<td>Outer Radius</td>\n<td>24 - 0\n</td></tr>\n<tr>\n<td>Outer Durable</td>\n<td>24 - 0\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Inner Radius</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Outer Radius</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Light</a></span>\n</td></tr>\n<tr>\n<td>Shockwave</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<th colspan="2">AoE Effect\n</th></tr>\n<tr>\n<td>Demolition Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>5\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-projectile" id="SMALL_PLASMA_BOLT_P1">\n<tbody><tr>\n<th colspan="2">SMALL PLASMA BOLT P1\n</th></tr>\n<tr>\n<th colspan="2">Projectile\n</th></tr>\n<tr>\n<td>Caliber</td>\n<td>20 mm\n</td></tr>\n<tr>\n<td>Mass</td>\n<td>25 g\n</td></tr>\n<tr>\n<td>Initial Velocity</td>\n<td>550 m/s\n</td></tr>\n<tr>\n<td>Drag Factor</td>\n<td>150%\n</td></tr>\n<tr>\n<td>Gravity Factor</td>\n<td>100%\n</td></tr>\n<tr>\n<td>Penetration Slowdown</td>\n<td>35%\n</td></tr>\n<tr>\n<td>Explosion On Impact</td>\n<td><span class="remote-trigger" data-target="SMALL_PLASMA_BOLT_P1_IE"><span class="remote-text">SMALL PLASMA BOLT_P1_IE</span></span>\n</td></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Standard</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: default;">150 Ballistic</span></a>\n</td></tr>\n<tr>\n<td>vs. Durable</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: default;">75 Ballistic</span></a>\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Direct</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Slight Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Large Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Extreme Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<th colspan="2">Special Effects\n</th></tr>\n<tr>\n<td>Demolition Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>20\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>10\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-explosion" id="SMALL_PLASMA_BOLT_P1_IE">\n<tbody><tr>\n<th colspan="2">SMALL PLASMA BOLT P1 IE\n</th></tr>\n<tr>\n<th colspan="2">Area of Effect\n</th></tr>\n<tr>\n<td>Inner Radius</td>\n<td>1 m\n</td></tr>\n<tr>\n<td>Outer Radius</td>\n<td>2 m\n</td></tr>\n<tr>\n<td>Shockwave Radius</td>\n<td>2 m\n</td></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Damage Element</td>\n<td>None\n</td></tr>\n<tr>\n<td>Inner Radius</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: orange;">75 Explosion</span></a>\n</td></tr>\n<tr>\n<td>Inner Durable</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: orange;">75 Explosion</span></a>\n</td></tr>\n<tr>\n<td>Outer Radius</td>\n<td>74 - 0\n</td></tr>\n<tr>\n<td>Outer Durable</td>\n<td>74 - 0\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Inner Radius</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Outer Radius</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Light</a></span>\n</td></tr>\n<tr>\n<td>Shockwave</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<th colspan="2">AoE Effect\n</th></tr>\n<tr>\n<td>Demolition Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>7\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-projectile" id="SMALL_PLASMA_BOLT_P2">\n<tbody><tr>\n<th colspan="2">SMALL PLASMA BOLT P2\n</th></tr>\n<tr>\n<th colspan="2">Projectile\n</th></tr>\n<tr>\n<td>Caliber</td>\n<td>20 mm\n</td></tr>\n<tr>\n<td>Mass</td>\n<td>25 g\n</td></tr>\n<tr>\n<td>Initial Velocity</td>\n<td>350 m/s\n</td></tr>\n<tr>\n<td>Drag Factor</td>\n<td>150%\n</td></tr>\n<tr>\n<td>Gravity Factor</td>\n<td>100%\n</td></tr>\n<tr>\n<td>Penetration Slowdown</td>\n<td>35%\n</td></tr>\n<tr>\n<td>Explosion On Impact</td>\n<td><span class="remote-trigger" data-target="SMALL_PLASMA_BOLT_P2_IE"><span class="remote-text">SMALL PLASMA BOLT_P2_IE</span></span>\n</td></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Standard</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: default;">150 Ballistic</span></a>\n</td></tr>\n<tr>\n<td>vs. Durable</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: default;">75 Ballistic</span></a>\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Direct</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Slight Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Large Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Extreme Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<th colspan="2">Special Effects\n</th></tr>\n<tr>\n<td>Demolition Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>20\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>10\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-explosion" id="SMALL_PLASMA_BOLT_P2_IE">\n<tbody><tr>\n<th colspan="2">SMALL PLASMA BOLT P2 IE\n</th></tr>\n<tr>\n<th colspan="2">Area of Effect\n</th></tr>\n<tr>\n<td>Inner Radius</td>\n<td>2.9 m\n</td></tr>\n<tr>\n<td>Outer Radius</td>\n<td>3 m\n</td></tr>\n<tr>\n<td>Shockwave Radius</td>\n<td>4 m\n</td></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Damage Element</td>\n<td>None\n</td></tr>\n<tr>\n<td>Inner Radius</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: orange;">225 Explosion</span></a>\n</td></tr>\n<tr>\n<td>Inner Durable</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: orange;">225 Explosion</span></a>\n</td></tr>\n<tr>\n<td>Outer Radius</td>\n<td>224 - 0\n</td></tr>\n<tr>\n<td>Outer Durable</td>\n<td>224 - 0\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Inner Radius</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Outer Radius</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Light</a></span>\n</td></tr>\n<tr>\n<td>Shockwave</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<th colspan="2">AoE Effect\n</th></tr>\n<tr>\n<td>Demolition Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>35\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>30\n</td></tr>\n</tbody></table>'
    ]
  },
  {
    displayName: 'SG-22 Bushwhacker',
    type: 'Equipment',
    category: 'secondary',
    tags: [
      'Shotgun'
    ],
    warbondCode: 'warbond8',
    internalName: 'sg22bushwhacker',
    imageUrl: 'equipment/sg22bushwhacker.png',
    tier: 'b',
    wikiSlug: 'SG-22_Bushwhacker',
    hoverTexts: [
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-weapon" data-parent="first">\n<tbody><tr>\n<th colspan="2">SG-22 BUSHWHACKER\n</th></tr>\n<tr>\n<td>Fire Rate</td>\n<td>650  rpm\n</td></tr>\n<tr>\n<td>Recoil</td>\n<td>107.5\n</td></tr>\n<tr>\n<td>Horizontal Recoil</td>\n<td>45\n</td></tr>\n<tr>\n<td>Vertical Recoil</td>\n<td>170\n</td></tr>\n<tr>\n<td>Spread</td>\n<td>↔[200.00]  ↕[150.00]\n</td></tr>\n<tr>\n<td>Sway</td>\n<td>1.3\n</td></tr>\n<tr>\n<td>Ergonomics</td>\n<td>65\n</td></tr>\n<tr>\n<td>Capacity</td>\n<td>3\n</td></tr>\n<tr>\n<td>Spare Rounds</td>\n<td>30\n</td></tr>\n<tr>\n<td>Starting Rounds</td>\n<td>30\n</td></tr>\n<tr>\n<td>Rounds from Supply</td>\n<td>30\n</td></tr>\n<tr>\n<td>Rounds from Ammo Box</td>\n<td>15\n</td></tr>\n<tr>\n<th colspan="2">Attacks\n</th></tr>\n<tr>\n<td>*<span class="remote-trigger" data-target="BUCKSHOT_P1"><span class="remote-text">BUCKSHOT P1</span></span></td>\n<td>Projectile\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-projectile" id="BUCKSHOT_P1">\n<tbody><tr>\n<th colspan="2">BUCKSHOT P1\n</th></tr>\n<tr>\n<th colspan="2">Projectile\n</th></tr>\n<tr>\n<td>Pellets</td>\n<td>x 9\n</td></tr>\n<tr>\n<td>Caliber</td>\n<td>8 mm\n</td></tr>\n<tr>\n<td>Mass</td>\n<td>6 g\n</td></tr>\n<tr>\n<td>Initial Velocity</td>\n<td>385 m/s\n</td></tr>\n<tr>\n<td>Drag Factor</td>\n<td>50%\n</td></tr>\n<tr>\n<td>Gravity Factor</td>\n<td>100%\n</td></tr>\n<tr>\n<td>Penetration Slowdown</td>\n<td>25%\n</td></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Standard</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: default;">45 Ballistic</span></a>\n</td></tr>\n<tr>\n<td>vs. Durable</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: default;">12 Ballistic</span></a>\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Direct</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Light</a></span>\n</td></tr>\n<tr>\n<td>Slight Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Light</a></span>\n</td></tr>\n<tr>\n<td>Large Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Light</a></span>\n</td></tr>\n<tr>\n<td>Extreme Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<th colspan="2">Special Effects\n</th></tr>\n<tr>\n<td>Demolition Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>35\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>30\n</td></tr>\n</tbody></table>'
    ]
  },
  {
    displayName: 'P-19 Redeemer',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond3',
    internalName: 'p19redeemer',
    imageUrl: 'equipment/p19redeemer.png',
    tier: 'b',
    wikiSlug: 'P-19_Redeemer',
    hoverTexts: [
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-weapon">\n<tbody><tr>\n<th colspan="2">P-19 Redeemer\n</th></tr>\n<tr>\n<td>Fire Rate</td>\n<td>1100 rpm\n</td></tr>\n<tr>\n<td>Recoil</td>\n<td>15\n</td></tr>\n<tr>\n<td>Sway</td>\n<td>1.2\n</td></tr>\n<tr>\n<td>Ergonomics</td>\n<td>95\n</td></tr>\n<tr>\n<td>Capacity</td>\n<td>31\n</td></tr>\n<tr>\n<td>Reload Time</td>\n<td>2.1  s\n</td></tr>\n<tr>\n<td>Tactical Reload</td>\n<td>1.4 s\n</td></tr>\n<tr>\n<td>Spare Magazines</td>\n<td>4\n</td></tr>\n<tr>\n<td>Starting Magazines</td>\n<td>4\n</td></tr>\n<tr>\n<td>Mags from Supply</td>\n<td>4\n</td></tr>\n<tr>\n<td>Mags from Ammo Box</td>\n<td>2\n</td></tr>\n<tr>\n<th colspan="2">Attacks\n</th></tr>\n<tr>\n<td>Pistol 9x20mm Full Metal Jacket</td>\n<td>Projectile\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-projectile">\n<tbody><tr>\n<th colspan="2">Pistol 9x20mm Full Metal Jacket\n</th></tr>\n<tr>\n<th colspan="2">Projectile\n</th></tr>\n<tr>\n<td>Caliber</td>\n<td>9 mm\n</td></tr>\n<tr>\n<td>Mass</td>\n<td>7 g\n</td></tr>\n<tr>\n<td>Initial Velocity</td>\n<td>375 m/s\n</td></tr>\n<tr>\n<td>Drag Factor</td>\n<td>60%\n</td></tr>\n<tr>\n<td>Gravity Factor</td>\n<td>100%\n</td></tr>\n<tr>\n<td>Penetration Slowdown</td>\n<td>25%\n</td></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Standard</td>\n<td><a title="Damage"></a>60 Damage\n</td></tr>\n<tr>\n<td>vs. Durable</td>\n<td><a title="Damage"></a>5 Damage\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Direct</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Light</a></span>\n</td></tr>\n<tr>\n<td>Slight Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Light</a></span>\n</td></tr>\n<tr>\n<td>Large Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Light</a></span>\n</td></tr>\n<tr>\n<td>Extreme Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<th colspan="2">Special Effects\n</th></tr>\n<tr>\n<td>Demolition Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>4\n</td></tr>\n</tbody></table>'
    ]
  },
  {
    displayName: 'GP-31 Grenade Pistol',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond6',
    internalName: 'gp31grenadepistol',
    imageUrl: 'equipment/gp31grenadepistol.png',
    tier: 'a',
    wikiSlug: 'GP-31_Grenade_Pistol',
    hoverTexts: [
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-weapon" data-parent="first">\n<tbody><tr>\n<th colspan="2">GP-31 GRENADE PISTOL\n</th></tr>\n<tr>\n<td>Fire Rate</td>\n<td>900  rpm\n</td></tr>\n<tr>\n<td>Recoil</td>\n<td>30.75\n</td></tr>\n<tr>\n<td>Horizontal Recoil</td>\n<td>11.5\n</td></tr>\n<tr>\n<td>Vertical Recoil</td>\n<td>50\n</td></tr>\n<tr>\n<td>Spread</td>\n<td>↔[30.00]  ↕[30.00]\n</td></tr>\n<tr>\n<td>Sway</td>\n<td>1.2\n</td></tr>\n<tr>\n<td>Ergonomics</td>\n<td>95\n</td></tr>\n<tr>\n<td>Capacity</td>\n<td>1\n</td></tr>\n<tr>\n<td>Spare Rounds</td>\n<td>6\n</td></tr>\n<tr>\n<td>Starting Rounds</td>\n<td>4\n</td></tr>\n<tr>\n<td>Rounds from Supply</td>\n<td>4\n</td></tr>\n<tr>\n<td>Rounds from Ammo Box</td>\n<td>2\n</td></tr>\n<tr>\n<th colspan="2">Attacks\n</th></tr>\n<tr>\n<td>*<span class="remote-trigger" data-target="40mm_HEAT_GRENADE_P"><span class="remote-text">40mm HEAT GRENADE P</span></span></td>\n<td>Projectile\n</td></tr>\n<tr>\n<td>**<span class="remote-trigger" data-target="40mm_HEAT_GRENADE_P_IE"><span class="remote-text">40mm HEAT GRENADE P IE</span></span></td>\n<td>Explosion\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-projectile" id="40mm_HEAT_GRENADE_P">\n<tbody><tr>\n<th colspan="2">40mm HEAT GRENADE P\n</th></tr>\n<tr>\n<th colspan="2">Projectile\n</th></tr>\n<tr>\n<td>Caliber</td>\n<td>40 mm\n</td></tr>\n<tr>\n<td>Mass</td>\n<td>50 g\n</td></tr>\n<tr>\n<td>Initial Velocity</td>\n<td>100 m/s\n</td></tr>\n<tr>\n<td>Drag Factor</td>\n<td>120%\n</td></tr>\n<tr>\n<td>Gravity Factor</td>\n<td>100%\n</td></tr>\n<tr>\n<td>Penetration Slowdown</td>\n<td>25%\n</td></tr>\n<tr>\n<td>Explosion On Impact</td>\n<td><span class="remote-trigger" data-target="40mm_HEAT_GRENADE_P_IE"><span class="remote-text">40mm HEAT GRENADE_P_IE</span></span>\n</td></tr>\n<tr>\n<td>Explode After</td>\n<td><span class="remote-trigger" data-target="40mm_HEAT_GRENADE_P_IE"><span class="remote-text">40mm HEAT GRENADE_P_IE</span></span>\n</td></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Standard</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: default;">250 Ballistic</span></a>\n</td></tr>\n<tr>\n<td>vs. Durable</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: default;">250 Ballistic</span></a>\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Direct</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Slight Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Large Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Extreme Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<th colspan="2">Special Effects\n</th></tr>\n<tr>\n<td>Demolition Force</td>\n<td>30\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>40\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>10\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-explosion" id="40mm_HEAT_GRENADE_P_IE">\n<tbody><tr>\n<th colspan="2">40mm HEAT GRENADE P IE\n</th></tr>\n<tr>\n<th colspan="2">Area of Effect\n</th></tr>\n<tr>\n<td>Inner Radius</td>\n<td>2.25 m\n</td></tr>\n<tr>\n<td>Outer Radius</td>\n<td>6.5 m\n</td></tr>\n<tr>\n<td>Shockwave Radius</td>\n<td>8 m\n</td></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Damage Element</td>\n<td>None\n</td></tr>\n<tr>\n<td>Inner Radius</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: orange;">400 Explosion</span></a>\n</td></tr>\n<tr>\n<td>Inner Durable</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: orange;">400 Explosion</span></a>\n</td></tr>\n<tr>\n<td>Outer Radius</td>\n<td>399 - 0\n</td></tr>\n<tr>\n<td>Outer Durable</td>\n<td>399 - 0\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Inner Radius</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Outer Radius</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Light</a></span>\n</td></tr>\n<tr>\n<td>Shockwave</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<th colspan="2">AoE Effect\n</th></tr>\n<tr>\n<td>Demolition Force</td>\n<td>30\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>25\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>30\n</td></tr>\n</tbody></table>'
    ]
  },
  {
    displayName: 'P-113 Verdict',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond7',
    internalName: 'p113verdict',
    imageUrl: 'equipment/p113verdict.png',
    tier: 'a',
    wikiSlug: 'P-113_Verdict',
    hoverTexts: [
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-weapon" data-parent="first">\n<tbody><tr>\n<th colspan="2">P-113 VERDICT\n</th></tr>\n<tr>\n<td>Fire Rate</td>\n<td>450  rpm\n</td></tr>\n<tr>\n<td>Recoil</td>\n<td>31.25\n</td></tr>\n<tr>\n<td>Horizontal Recoil</td>\n<td>15\n</td></tr>\n<tr>\n<td>Vertical Recoil</td>\n<td>47.5\n</td></tr>\n<tr>\n<td>Spread</td>\n<td>↔[8.00]  ↕[8.00]\n</td></tr>\n<tr>\n<td>Sway</td>\n<td>1.2\n</td></tr>\n<tr>\n<td>Ergonomics</td>\n<td>100\n</td></tr>\n<tr>\n<td>Capacity</td>\n<td>10\n</td></tr>\n<tr>\n<td>Spare Magazines</td>\n<td>8\n</td></tr>\n<tr>\n<td>Starting Magazines</td>\n<td>4\n</td></tr>\n<tr>\n<td>Mags from Supply</td>\n<td>8\n</td></tr>\n<tr>\n<td>Mags from Ammo Box</td>\n<td>4\n</td></tr>\n<tr>\n<th colspan="2">Attacks\n</th></tr>\n<tr>\n<td>*<span class="remote-trigger" data-target="12x25mm_FULL_METAL_JACKET_P"><span class="remote-text">12x25mm FULL METAL JACKET P</span></span></td>\n<td>Projectile\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-projectile" id="12x25mm_FULL_METAL_JACKET_P">\n<tbody><tr>\n<th colspan="2">12x25mm FULL METAL JACKET P\n</th></tr>\n<tr>\n<th colspan="2">Projectile\n</th></tr>\n<tr>\n<td>Caliber</td>\n<td>12 mm\n</td></tr>\n<tr>\n<td>Mass</td>\n<td>15 g\n</td></tr>\n<tr>\n<td>Initial Velocity</td>\n<td>285 m/s\n</td></tr>\n<tr>\n<td>Drag Factor</td>\n<td>60%\n</td></tr>\n<tr>\n<td>Gravity Factor</td>\n<td>100%\n</td></tr>\n<tr>\n<td>Penetration Slowdown</td>\n<td>25%\n</td></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Standard</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: default;">125 Ballistic</span></a>\n</td></tr>\n<tr>\n<td>vs. Durable</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: default;">32 Ballistic</span></a>\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Direct</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Slight Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Large Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Extreme Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<th colspan="2">Special Effects\n</th></tr>\n<tr>\n<td>Demolition Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>15\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>10\n</td></tr>\n</tbody></table>'
    ]
  },
  {
    displayName: 'P-4 Senator',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond4',
    internalName: 'p4senator',
    imageUrl: 'equipment/p4senator.png',
    tier: 'a',
    wikiSlug: 'P-4_Senator',
    hoverTexts: [
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-weapon" data-parent="first">\n<tbody><tr>\n<th colspan="2">P-4 SENATOR\n</th></tr>\n<tr>\n<td>Fire Rate</td>\n<td>200  rpm\n</td></tr>\n<tr>\n<td>Recoil</td>\n<td>30.75\n</td></tr>\n<tr>\n<td>Horizontal Recoil</td>\n<td>11.5\n</td></tr>\n<tr>\n<td>Vertical Recoil</td>\n<td>50\n</td></tr>\n<tr>\n<td>Spread</td>\n<td>↔[8.00]  ↕[8.00]\n</td></tr>\n<tr>\n<td>Sway</td>\n<td>1.3\n</td></tr>\n<tr>\n<td>Ergonomics</td>\n<td>75\n</td></tr>\n<tr>\n<td>Capacity</td>\n<td>6\n</td></tr>\n<tr>\n<td>Spare Rounds</td>\n<td>40\n</td></tr>\n<tr>\n<td>Starting Rounds</td>\n<td>32\n</td></tr>\n<tr>\n<td>Rounds from Supply</td>\n<td>40\n</td></tr>\n<tr>\n<td>Rounds from Ammo Box</td>\n<td>20\n</td></tr>\n<tr>\n<th colspan="2">Attacks\n</th></tr>\n<tr>\n<td>*<span class="remote-trigger" data-target="13x40mm_FULL_METAL_JACKET_P"><span class="remote-text">13x40mm FULL METAL JACKET P</span></span></td>\n<td>Projectile\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-projectile" id="13x40mm_FULL_METAL_JACKET_P">\n<tbody><tr>\n<th colspan="2">13x40mm FULL METAL JACKET P\n</th></tr>\n<tr>\n<th colspan="2">Projectile\n</th></tr>\n<tr>\n<td>Caliber</td>\n<td>12 mm\n</td></tr>\n<tr>\n<td>Mass</td>\n<td>15 g\n</td></tr>\n<tr>\n<td>Initial Velocity</td>\n<td>550 m/s\n</td></tr>\n<tr>\n<td>Drag Factor</td>\n<td>60%\n</td></tr>\n<tr>\n<td>Gravity Factor</td>\n<td>100%\n</td></tr>\n<tr>\n<td>Penetration Slowdown</td>\n<td>25%\n</td></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Standard</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: default;">200 Ballistic</span></a>\n</td></tr>\n<tr>\n<td>vs. Durable</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: default;">70 Ballistic</span></a>\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Direct</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Heavy</a></span>\n</td></tr>\n<tr>\n<td>Slight Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Heavy</a></span>\n</td></tr>\n<tr>\n<td>Large Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Heavy</a></span>\n</td></tr>\n<tr>\n<td>Extreme Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<th colspan="2">Special Effects\n</th></tr>\n<tr>\n<td>Demolition Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>20\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>10\n</td></tr>\n</tbody></table>'
    ]
  },
  {
    displayName: 'LAS-7 Dagger',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond5',
    internalName: 'las7dagger',
    imageUrl: 'equipment/las7dagger.png',
    tier: 'c',
    wikiSlug: 'LAS-7_Dagger',
    hoverTexts: [
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-weapon" data-parent="first">\n<tbody><tr>\n<th colspan="2">LAS-7 DAGGER\n</th></tr>\n<tr>\n<td>Recoil</td>\n<td>0\n</td></tr>\n<tr>\n<td>Horizontal Recoil</td>\n<td>0\n</td></tr>\n<tr>\n<td>Vertical Recoil</td>\n<td>0\n</td></tr>\n<tr>\n<td>Spread</td>\n<td>↔[10.00]  ↕[10.00]\n</td></tr>\n<tr>\n<td>Sway</td>\n<td>1.2\n</td></tr>\n<tr>\n<td>Ergonomics</td>\n<td>95\n</td></tr>\n<tr>\n<td>Spare Magazines</td>\n<td>3\n</td></tr>\n<tr>\n<td>Starting Magazines</td>\n<td>3\n</td></tr>\n<tr>\n<td>Mags from Supply</td>\n<td>6\n</td></tr>\n<tr>\n<td>Mags from Ammo Box</td>\n<td>3\n</td></tr>\n<tr>\n<th colspan="2">Heat Data\n</th></tr>\n<tr>\n<td>Overheats at</td>\n<td>100 °C\n</td></tr>\n<tr>\n<td>Warmup</td>\n<td>0.25 sec\n</td></tr>\n<tr>\n<td>Heat Per Second</td>\n<td>15 °C\n</td></tr>\n<tr>\n<td>Cool Per Sec</td>\n<td><span class="faction-icon" style="color: lightblue;"><a title="Extreme Cold"></a> 15</span> - 10 - <span class="faction-icon" style="color: orangered;"><a title="Intense Heat"></a> 7.5</span>\n</td></tr>\n<tr>\n<td>Cooldown After Overheat</td>\n<td>RELOAD NEEDED\n</td></tr>\n<tr>\n<th colspan="2">Attacks\n</th></tr>\n<tr>\n<td>*<span class="remote-trigger" data-target="LAS-7_DAGGER_B"><span class="remote-text">LAS-7 DAGGER B</span></span></td>\n<td>Beam\n</td></tr>\n<tr>\n<td>**<span class="remote-trigger" data-target="Fire"><span class="remote-text">Fire</span></span></td>\n<td>status\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-beam" id="LAS-7_DAGGER_B">\n<tbody><tr>\n<th colspan="2">LAS-7 DAGGER B\n</th></tr>\n<tr>\n<th colspan="2">Beam\n</th></tr>\n<tr>\n<td>Beam Range</td>\n<td>1000 m\n</td></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Standard</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: gold;">250 Laser</span></a>\n</td></tr>\n<tr>\n<td>vs. Durable</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: gold;">50 Laser</span></a>\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Direct</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Light</a></span>\n</td></tr>\n<tr>\n<td>Slight Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Light</a></span>\n</td></tr>\n<tr>\n<td>Large Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Light</a></span>\n</td></tr>\n<tr>\n<td>Extreme Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<th colspan="2">Special Effects\n</th></tr>\n<tr>\n<td>Status</td>\n<td><a title="Status Effects">Fire</a>\n</td></tr>\n<tr>\n<td>Status Strength</td>\n<td>1\n</td></tr>\n<tr>\n<td>Demolition Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>0\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>0\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-status" id="Fire">\n<tbody><tr>\n<th colspan="2">Fire\n</th></tr>\n<tr>\n<th colspan="2">Status\n</th></tr>\n<tr>\n<td>Status Strength</td>\n<td>5\n</td></tr>\n<tr>\n<td>Status Duration</td>\n<td>3 sec\n</td></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Element</td>\n<td>Fire\n</td></tr>\n<tr>\n<td>Standard</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: orangered;">100 Fire</span></a>\n</td></tr>\n<tr>\n<td>vs. Durable</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: orangered;">100 Fire</span></a>\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Direct</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Heavy</a></span>\n</td></tr>\n<tr>\n<td>Slight Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Heavy</a></span>\n</td></tr>\n<tr>\n<td>Large Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Heavy</a></span>\n</td></tr>\n<tr>\n<td>Extreme Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<th colspan="2">Special Effects\n</th></tr>\n<tr>\n<td>Demolition Force</td>\n<td>0\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>0\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>0\n</td></tr>\n</tbody></table>'
    ]
  },
  {
    displayName: 'LAS-58 Talon',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond14',
    internalName: 'las58talon',
    imageUrl: 'equipment/las58talon.png',
    tier: 'a',
    wikiSlug: 'LAS-58_Talon',
    hoverTexts: [
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-weapon" data-parent="first">\n<tbody><tr>\n<th colspan="2">LAS-58 TALON\n</th></tr>\n<tr>\n<td>Fire Rate</td>\n<td>750  rpm\n</td></tr>\n<tr>\n<td>Recoil</td>\n<td>1.75\n</td></tr>\n<tr>\n<td>Horizontal Recoil</td>\n<td>2\n</td></tr>\n<tr>\n<td>Vertical Recoil</td>\n<td>1.5\n</td></tr>\n<tr>\n<td>Spread</td>\n<td>↔[10.00]  ↕[10.00]\n</td></tr>\n<tr>\n<td>Sway</td>\n<td>1.2\n</td></tr>\n<tr>\n<td>Ergonomics</td>\n<td>95\n</td></tr>\n<tr>\n<td>Spare Magazines</td>\n<td>3\n</td></tr>\n<tr>\n<td>Starting Magazines</td>\n<td>2\n</td></tr>\n<tr>\n<td>Mags from Supply</td>\n<td>6\n</td></tr>\n<tr>\n<td>Mags from Ammo Box</td>\n<td>3\n</td></tr>\n<tr>\n<th colspan="2">Heat Data\n</th></tr>\n<tr>\n<td>Overheats at</td>\n<td>100 °C\n</td></tr>\n<tr>\n<td>Warmup</td>\n<td>0 sec\n</td></tr>\n<tr>\n<td>Heat Per Shot</td>\n<td>15 °C\n</td></tr>\n<tr>\n<td>Cool Per Sec</td>\n<td><span class="faction-icon" style="color: lightblue;"><a title="Extreme Cold"></a> 15</span> - 10 - <span class="faction-icon" style="color: orangered;"><a title="Intense Heat"></a> 7.5</span>\n</td></tr>\n<tr>\n<td>Cooldown After Overheat</td>\n<td>RELOAD NEEDED\n</td></tr>\n<tr>\n<th colspan="2">Attacks\n</th></tr>\n<tr>\n<td>*<span class="remote-trigger" data-target="LASER_P1"><span class="remote-text">LASER P1</span></span></td>\n<td>Projectile\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-projectile" id="LASER_P1">\n<tbody><tr>\n<th colspan="2">LASER P1\n</th></tr>\n<tr>\n<th colspan="2">Projectile\n</th></tr>\n<tr>\n<td>Caliber</td>\n<td>10 mm\n</td></tr>\n<tr>\n<td>Mass</td>\n<td>12 g\n</td></tr>\n<tr>\n<td>Initial Velocity</td>\n<td>1300 m/s\n</td></tr>\n<tr>\n<td>Drag Factor</td>\n<td>0%\n</td></tr>\n<tr>\n<td>Gravity Factor</td>\n<td>0%\n</td></tr>\n<tr>\n<td>Lifetime</td>\n<td>6 sec\n</td></tr>\n<tr>\n<td>Penetration Slowdown</td>\n<td>25%\n</td></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Standard</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: default;">200 Ballistic</span></a>\n</td></tr>\n<tr>\n<td>vs. Durable</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: default;">20 Ballistic</span></a>\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Direct</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Slight Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Large Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Extreme Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<th colspan="2">Special Effects\n</th></tr>\n<tr>\n<td>Demolition Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>10\n</td></tr>\n</tbody></table>'
    ]
  },
  {
    displayName: 'P-72 Crisper',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond9',
    internalName: 'p72crisper',
    imageUrl: 'equipment/p72crisper.png',
    tier: 'b',
    wikiSlug: 'P-72_Crisper',
    hoverTexts: [
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-weapon">\n<tbody><tr>\n<th colspan="2">P-72 Crisper\n</th></tr>\n<tr>\n<td>Sway</td>\n<td>1.2\n</td></tr>\n<tr>\n<td>Ergonomics</td>\n<td>95\n</td></tr>\n<tr>\n<td>Capacity</td>\n<td>30\n</td></tr>\n<tr>\n<td>Fire Limit</td>\n<td>3.7 s\n</td></tr>\n<tr>\n<td>Reload Time</td>\n<td>2.35  s\n</td></tr>\n<tr>\n<td>Spare Magazines</td>\n<td>4\n</td></tr>\n<tr>\n<td>Starting Magazines</td>\n<td>2\n</td></tr>\n<tr>\n<td>Mags from Supply</td>\n<td>4\n</td></tr>\n<tr>\n<td>Mags from Ammo Box</td>\n<td>2\n</td></tr>\n<tr>\n<th colspan="2">Attacks\n</th></tr>\n<tr>\n<td>Crisper</td>\n<td>Damage\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-damage">\n<tbody><tr>\n<th colspan="2">Crisper\n</th></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Element</td>\n<td>Fire\n</td></tr>\n<tr>\n<td>Standard</td>\n<td>150 DPS\n</td></tr>\n<tr>\n<td>vs. Durable</td>\n<td>150 DPS\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Direct</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Heavy</a></span>\n</td></tr>\n<tr>\n<td>Slight Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Heavy</a></span>\n</td></tr>\n<tr>\n<td>Large Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Heavy</a></span>\n</td></tr>\n<tr>\n<td>Extreme Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<th colspan="2">Special Effects\n</th></tr>\n<tr>\n<td>Status</td>\n<td><a title="Status Effects">Fire</a>\n</td></tr>\n<tr>\n<td>Status Strength</td>\n<td>2\n</td></tr>\n<tr>\n<td>Demolition Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>5\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>5\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-damage">\n<tbody><tr>\n<th colspan="2">DPS Fire\n</th></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Element</td>\n<td>Fire\n</td></tr>\n<tr>\n<td>Standard</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: orangered;">100 Fire</span></a>\n</td></tr>\n<tr>\n<td>vs. Durable</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: orangered;">100 Fire</span></a>\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Direct</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Heavy</a></span>\n</td></tr>\n<tr>\n<td>Slight Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Heavy</a></span>\n</td></tr>\n<tr>\n<td>Large Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Heavy</a></span>\n</td></tr>\n<tr>\n<td>Extreme Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<th colspan="2">Special Effects\n</th></tr>\n<tr>\n<td>Demolition Force</td>\n<td>0\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>0\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>0\n</td></tr>\n</tbody></table>'
    ]
  },
  {
    displayName: 'GP-20 Ultimatum',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond13',
    internalName: 'gp31ultimatum',
    imageUrl: 'equipment/gp31ultimatum.png',
    tier: 's',
    wikiSlug: 'GP-31_Ultimatum',
    hoverTexts: [
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-weapon" data-parent="first">\n<tbody><tr>\n<th colspan="2">GP-20 ULTIMATUM\n</th></tr>\n<tr>\n<td>Fire Rate</td>\n<td>900  rpm\n</td></tr>\n<tr>\n<td>Recoil</td>\n<td>30.75\n</td></tr>\n<tr>\n<td>Horizontal Recoil</td>\n<td>11.5\n</td></tr>\n<tr>\n<td>Vertical Recoil</td>\n<td>50\n</td></tr>\n<tr>\n<td>Spread</td>\n<td>↔[50.00]  ↕[50.00]\n</td></tr>\n<tr>\n<td>Sway</td>\n<td>1.3\n</td></tr>\n<tr>\n<td>Ergonomics</td>\n<td>35\n</td></tr>\n<tr>\n<td>Capacity</td>\n<td>1\n</td></tr>\n<tr>\n<td>Spare Magazines</td>\n<td>1\n</td></tr>\n<tr>\n<td>Starting Magazines</td>\n<td>0\n</td></tr>\n<tr>\n<td>Mags from Supply</td>\n<td>1\n</td></tr>\n<tr>\n<td>Mags from Ammo Box</td>\n<td>1\n</td></tr>\n<tr>\n<th colspan="2">Attacks\n</th></tr>\n<tr>\n<td>*<span class="remote-trigger" data-target="GP-20_P"><span class="remote-text">GP-20 P</span></span></td>\n<td>Projectile\n</td></tr>\n<tr>\n<td>**<span class="remote-trigger" data-target="GP-20_P_IE"><span class="remote-text">GP-20 P IE</span></span></td>\n<td>Explosion\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-projectile" id="GP-20_P">\n<tbody><tr>\n<th colspan="2">GP-20 P\n</th></tr>\n<tr>\n<th colspan="2">Projectile\n</th></tr>\n<tr>\n<td>Caliber</td>\n<td>80 mm\n</td></tr>\n<tr>\n<td>Mass</td>\n<td>500 g\n</td></tr>\n<tr>\n<td>Initial Velocity</td>\n<td>20 m/s\n</td></tr>\n<tr>\n<td>Drag Factor</td>\n<td>50%\n</td></tr>\n<tr>\n<td>Gravity Factor</td>\n<td>100%\n</td></tr>\n<tr>\n<td>Penetration Slowdown</td>\n<td>25%\n</td></tr>\n<tr>\n<td>Explosion On Impact</td>\n<td><span class="remote-trigger" data-target="GP-20_P_IE"><span class="remote-text">GP-20_P_IE</span></span>\n</td></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Standard</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: default;">1000 Ballistic</span></a>\n</td></tr>\n<tr>\n<td>vs. Durable</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: default;">1000 Ballistic</span></a>\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Direct</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Anti-Tank II</a></span>\n</td></tr>\n<tr>\n<td>Slight Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Anti-Tank II</a></span>\n</td></tr>\n<tr>\n<td>Large Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Anti-Tank II</a></span>\n</td></tr>\n<tr>\n<td>Extreme Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Anti-Tank II</a></span>\n</td></tr>\n<tr>\n<th colspan="2">Special Effects\n</th></tr>\n<tr>\n<td>Demolition Force</td>\n<td>40\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>50\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>20\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-explosion" id="GP-20_P_IE">\n<tbody><tr>\n<th colspan="2">GP-20 P IE\n</th></tr>\n<tr>\n<th colspan="2">Area of Effect\n</th></tr>\n<tr>\n<td>Inner Radius</td>\n<td>2 m\n</td></tr>\n<tr>\n<td>Outer Radius</td>\n<td>12 m\n</td></tr>\n<tr>\n<td>Shockwave Radius</td>\n<td>25 m\n</td></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Damage Element</td>\n<td>None\n</td></tr>\n<tr>\n<td>Inner Radius</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: orange;">2000 Explosion</span></a>\n</td></tr>\n<tr>\n<td>Inner Durable</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: orange;">2000 Explosion</span></a>\n</td></tr>\n<tr>\n<td>Outer Radius</td>\n<td>1999 - 0\n</td></tr>\n<tr>\n<td>Outer Durable</td>\n<td>1999 - 0\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Inner Radius</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Anti-Tank II</a></span>\n</td></tr>\n<tr>\n<td>Outer Radius</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Anti-Tank I</a></span>\n</td></tr>\n<tr>\n<td>Shockwave</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Anti-Tank II</a></span>\n</td></tr>\n<tr>\n<th colspan="2">AoE Effect\n</th></tr>\n<tr>\n<td>Demolition Force</td>\n<td>40\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>70\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>60\n</td></tr>\n</tbody></table>'
    ]
  },
  {
    displayName: 'P-92 Warrant',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond16',
    internalName: 'p92warrant',
    imageUrl: 'equipment/p92warrant.png',
    tier: 'b',
    wikiSlug: 'P-92_Warrant',
    hoverTexts: [
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-weapon" data-parent="first">\n<tbody><tr>\n<th colspan="2">P-92 WARRANT\n</th></tr>\n<tr>\n<td>Fire Rate</td>\n<td>450  rpm\n</td></tr>\n<tr>\n<td>Recoil</td>\n<td>31.25\n</td></tr>\n<tr>\n<td>Horizontal Recoil</td>\n<td>15\n</td></tr>\n<tr>\n<td>Vertical Recoil</td>\n<td>47.5\n</td></tr>\n<tr>\n<td>Spread</td>\n<td>↔[8.00]  ↕[8.00]\n</td></tr>\n<tr>\n<td>Sway</td>\n<td>1\n</td></tr>\n<tr>\n<td>Ergonomics</td>\n<td>100\n</td></tr>\n<tr>\n<td>Capacity</td>\n<td>13\n</td></tr>\n<tr>\n<td>Spare Magazines</td>\n<td>7\n</td></tr>\n<tr>\n<td>Starting Magazines</td>\n<td>4\n</td></tr>\n<tr>\n<td>Mags from Supply</td>\n<td>7\n</td></tr>\n<tr>\n<td>Mags from Ammo Box</td>\n<td>3\n</td></tr>\n<tr>\n<th colspan="2">Attacks\n</th></tr>\n<tr>\n<td>*<span class="remote-trigger" data-target="Guided_P"><span class="remote-text">Guided P</span></span></td>\n<td>Projectile\n</td></tr>\n<tr>\n<td>*<span class="remote-trigger" data-target="Non-Guided_P"><span class="remote-text">Non-Guided P</span></span></td>\n<td>Projectile\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-projectile" id="Guided_P">\n<tbody><tr>\n<th colspan="2">Guided P\n</th></tr>\n<tr>\n<th colspan="2">Projectile\n</th></tr>\n<tr>\n<td>Caliber</td>\n<td>12 mm\n</td></tr>\n<tr>\n<td>Mass</td>\n<td>15 g\n</td></tr>\n<tr>\n<td>Initial Velocity</td>\n<td>285 m/s\n</td></tr>\n<tr>\n<td>Drag Factor</td>\n<td>30%\n</td></tr>\n<tr>\n<td>Gravity Factor</td>\n<td>100%\n</td></tr>\n<tr>\n<td>Penetration Slowdown</td>\n<td>25%\n</td></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Standard</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: default;">80 Ballistic</span></a>\n</td></tr>\n<tr>\n<td>vs. Durable</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: default;">20 Ballistic</span></a>\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Direct</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Slight Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Large Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Extreme Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<th colspan="2">Special Effects\n</th></tr>\n<tr>\n<td>Demolition Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>15\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>10\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-projectile" id="Non-Guided_P">\n<tbody><tr>\n<th colspan="2">Non-Guided P\n</th></tr>\n<tr>\n<th colspan="2">Projectile\n</th></tr>\n<tr>\n<td>Caliber</td>\n<td>12 mm\n</td></tr>\n<tr>\n<td>Mass</td>\n<td>15 g\n</td></tr>\n<tr>\n<td>Initial Velocity</td>\n<td>285 m/s\n</td></tr>\n<tr>\n<td>Drag Factor</td>\n<td>30%\n</td></tr>\n<tr>\n<td>Gravity Factor</td>\n<td>100%\n</td></tr>\n<tr>\n<td>Penetration Slowdown</td>\n<td>25%\n</td></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Standard</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: default;">80 Ballistic</span></a>\n</td></tr>\n<tr>\n<td>vs. Durable</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: default;">20 Ballistic</span></a>\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Direct</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Slight Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Large Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Medium</a></span>\n</td></tr>\n<tr>\n<td>Extreme Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<th colspan="2">Special Effects\n</th></tr>\n<tr>\n<td>Demolition Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>15\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>10\n</td></tr>\n</tbody></table>'
    ]
  },
  {
    displayName: 'M6C/SOCOM Pistol',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond19',
    internalName: 'm6csocompistol',
    imageUrl: 'equipment/m6csocompistol.png',
    tier: 'b',
    wikiSlug: 'M6C/SOCOM_Pistol',
    hoverTexts: [
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-weapon" data-parent="first">\n<tbody><tr>\n<th colspan="2">M6C/SOCOM PISTOL\n</th></tr>\n<tr>\n<td>Fire Rate</td>\n<td>900  rpm\n</td></tr>\n<tr>\n<td>Recoil</td>\n<td>19.5\n</td></tr>\n<tr>\n<td>Horizontal Recoil</td>\n<td>11.5\n</td></tr>\n<tr>\n<td>Vertical Recoil</td>\n<td>27.5\n</td></tr>\n<tr>\n<td>Spread</td>\n<td>↔[10.00]  ↕[10.00]\n</td></tr>\n<tr>\n<td>Sway</td>\n<td>1.2\n</td></tr>\n<tr>\n<td>Ergonomics</td>\n<td>100\n</td></tr>\n<tr>\n<td>Capacity</td>\n<td>12\n</td></tr>\n<tr>\n<td>Spare Magazines</td>\n<td>8\n</td></tr>\n<tr>\n<td>Starting Magazines</td>\n<td>5\n</td></tr>\n<tr>\n<td>Mags from Supply</td>\n<td>8\n</td></tr>\n<tr>\n<td>Mags from Ammo Box</td>\n<td>4\n</td></tr>\n<tr>\n<th colspan="2">Attacks\n</th></tr>\n<tr>\n<td>*<span class="remote-trigger" data-target="M6CSOCOM_P"><span class="remote-text">M6C/SOCOM P</span></span></td>\n<td>Projectile\n</td></tr>\n</tbody></table>',
      '<table class="wikitable tableleftjustified Secondcolumnright table-weapon-stats attack-data-table-projectile" id="M6CSOCOM_P">\n<tbody><tr>\n<th colspan="2">M6C/SOCOM P\n</th></tr>\n<tr>\n<th colspan="2">Projectile\n</th></tr>\n<tr>\n<td>Caliber</td>\n<td>12 mm\n</td></tr>\n<tr>\n<td>Mass</td>\n<td>15 g\n</td></tr>\n<tr>\n<td>Initial Velocity</td>\n<td>285 m/s\n</td></tr>\n<tr>\n<td>Drag Factor</td>\n<td>60%\n</td></tr>\n<tr>\n<td>Gravity Factor</td>\n<td>100%\n</td></tr>\n<tr>\n<td>Penetration Slowdown</td>\n<td>25%\n</td></tr>\n<tr>\n<th colspan="2">Damage\n</th></tr>\n<tr>\n<td>Standard</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: default;">100 Ballistic</span></a>\n</td></tr>\n<tr>\n<td>vs. Durable</td>\n<td><a title="Damage"></a><a title="Damage"><span style="color: default;">25 Ballistic</span></a>\n</td></tr>\n<tr>\n<th colspan="2">Penetration\n</th></tr>\n<tr>\n<td>Direct</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Light</a></span>\n</td></tr>\n<tr>\n<td>Slight Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Light</a></span>\n</td></tr>\n<tr>\n<td>Large Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Light</a></span>\n</td></tr>\n<tr>\n<td>Extreme Angle</td>\n<td><span class="Templateicons"><a title="Damage"></a>&nbsp;<a title="Damage">Unarmored I</a></span>\n</td></tr>\n<tr>\n<th colspan="2">Special Effects\n</th></tr>\n<tr>\n<td>Demolition Force</td>\n<td>10\n</td></tr>\n<tr>\n<td>Stagger Force</td>\n<td>15\n</td></tr>\n<tr>\n<td>Push Force</td>\n<td>10\n</td></tr>\n</tbody></table>'
    ]
  }

];
