export function getStratagem(displayName) {
  return STRATAGEMS.find((item) => item.displayName === displayName);
}

export const STRATAGEMS = [
  {
    displayName: "Sterilizer",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbondCode: "warbond10",
    internalName: "tx41sterilizer",
    imageUrl: "stratagems/tx41sterilizer.svg",
    tier: "d",
  },
  {
    displayName: "Flamethrower",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbondCode: "none",
    internalName: "flam40flamethrower",
    imageUrl: "stratagems/flam40flamethrower.svg",
    tier: "b",
  },
  {
    displayName: "Speargun",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbondCode: "warbond20",
    internalName: "speargun",
    imageUrl: "stratagems/speargun.svg",
    tier: "a",
  },
  {
    displayName: "Laser Cannon",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbondCode: "none",
    internalName: "las98lasercannon",
    imageUrl: "stratagems/las98lasercannon.svg",
    tier: "b",
  },
  {
    displayName: "Stalwart",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbondCode: "none",
    internalName: "m105stalwart",
    imageUrl: "stratagems/m105stalwart.svg",
    tier: "b",
  },
  {
    displayName: "Machine Gun",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbondCode: "none",
    internalName: "mg43machinegun",
    imageUrl: "stratagems/mg43machinegun.svg",
    tier: "b",
  },
  {
    displayName: "Heavy Machine Gun",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbondCode: "none",
    internalName: "mg206heavymachinegun",
    imageUrl: "stratagems/mg206heavymachinegun.svg",
    tier: "c",
  },
  {
    displayName: "Arc Thrower",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbondCode: "none",
    internalName: "arc3arcthrower",
    imageUrl: "stratagems/arc3arcthrower.svg",
    tier: "c",
  },
  {
    displayName: "Grenade Launcher",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbondCode: "none",
    internalName: "gl21grenadelauncher",
    imageUrl: "stratagems/gl21grenadelauncher.svg",
    tier: "b",
  },
  {
    displayName: "De-Escalator",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbondCode: "warbond16",
    internalName: "gl52deescalator",
    imageUrl: "stratagems/gl52deescalator.svg",
    tier: "c",
  },
  {
    displayName: "Anti-Material Rifle",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbondCode: "none",
    internalName: "apw1antimaterielrifle",
    imageUrl: "stratagems/apw1antimaterielrifle.svg",
    tier: "c",
  },
  {
    displayName: "Railgun",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbondCode: "none",
    internalName: "rs422railgun",
    imageUrl: "stratagems/rs422railgun.svg",
    tier: "b",
  },
  {
    displayName: "Quasar Cannon",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbondCode: "none",
    internalName: "las99quasarcannon",
    imageUrl: "stratagems/las99quasarcannon.svg",
    tier: "s",
  },
  {
    displayName: "Epoch",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbondCode: "warbond17",
    internalName: "epoch",
    imageUrl: "stratagems/epoch.svg",
    tier: "b",
  },
  {
    displayName: "Expendable Anti-Tank",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbondCode: "none",
    internalName: "eat17expendableantitank",
    imageUrl: "stratagems/eat17expendableantitank.svg",
    tier: "a",
  },
  {
    displayName: "Commando",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbondCode: "none",
    internalName: "mls4xcommandorocketlauncher",
    imageUrl: "stratagems/mls4xcommandorocketlauncher.svg",
    tier: "a",
  },
  {
    displayName: "Expendable Napalm",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbondCode: "warbond20",
    internalName: "eat700expendablenapalm",
    imageUrl: "stratagems/eat700expendablenapalm.svg",
    tier: "a",
  },
  {
    displayName: "Solo Silo",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbondCode: "warbond20",
    internalName: "solosilo",
    imageUrl: "stratagems/solosilo.svg",
    tier: "s",
  },
  {
    displayName: "One True Flag",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbondCode: "warbond15",
    internalName: "onetrueflag",
    imageUrl: "stratagems/onetrueflag.svg",
    tier: "d",
    overrideCost: 1,
  },
  {
    displayName: "Airburst Rocket Launcher",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons", "Backpacks"],
    warbondCode: "none",
    internalName: "rl77airburstrocketlauncher",
    imageUrl: "stratagems/rl77airburstrocketlauncher.svg",
    tier: "b",
  },
  {
    displayName: "Autocannon",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons", "Backpacks"],
    warbondCode: "none",
    internalName: "ac8autocannon",
    imageUrl: "stratagems/ac8autocannon.svg",
    tier: "b",
  },
  {
    displayName: "W.A.S.P. Launcher",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons", "Backpacks"],
    warbondCode: "warbond18",
    internalName: "wasplauncher",
    imageUrl: "stratagems/wasplauncher.svg",
    tier: "c",
  },
  {
    displayName: "Recoilless Rifle",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons", "Backpacks"],
    warbondCode: "none",
    internalName: "gr8recoillessrifle",
    imageUrl: "stratagems/gr8recoillessrifle.svg",
    tier: "s",
  },
  {
    displayName: "Spear",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons", "Backpacks"],
    warbondCode: "none",
    internalName: "faf14spear",
    imageUrl: "stratagems/faf14spear.svg",
    tier: "a",
  },
  {
    displayName: "Guard Dog Breath",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbondCode: "warbond10",
    internalName: "axtx13guarddogdogbreath",
    imageUrl: "stratagems/axtx13guarddogdogbreath.svg",
    tier: "b",
  },
  {
    displayName: "Guard Dog Laser",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbondCode: "none",
    internalName: "axlas5guarddogrover",
    imageUrl: "stratagems/axlas5guarddogrover.svg",
    tier: "b",
  },
  {
    displayName: "Guard Dog Bullets",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbondCode: "none",
    internalName: "ad334guarddog",
    imageUrl: "stratagems/ad334guarddog.svg",
    tier: "a",
  },
  {
    displayName: "Guard Dog Arc",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbondCode: "warbond16",
    internalName: "guarddogarc",
    imageUrl: "stratagems/guarddogarc.svg",
    tier: "b",
  },
  {
    displayName: "Jump Pack",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbondCode: "none",
    internalName: "lift850jumppack",
    imageUrl: "stratagems/lift850jumppack.svg",
    tier: "a",
  },
  {
    displayName: "Hover Pack",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbondCode: "warbond14",
    internalName: "lift860hoverpack",
    imageUrl: "stratagems/lift860hoverpack.svg",
    tier: "b",
  },
  {
    displayName: "Warp Pack",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbondCode: "warbond17",
    internalName: "warppack",
    imageUrl: "stratagems/warppack.svg",
    tier: "s",
  },
  {
    displayName: "Supply Pack",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbondCode: "none",
    internalName: "b1supplypack",
    imageUrl: "stratagems/b1supplypack.svg",
    tier: "s",
  },
  {
    displayName: "Directional Shield",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbondCode: "warbond12",
    internalName: "sh51directionalshield",
    imageUrl: "stratagems/sh51directionalshield.svg",
    tier: "d",
  },
  {
    displayName: "Shield Generator Pack",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbondCode: "none",
    internalName: "sh20shieldgeneratorpack",
    imageUrl: "stratagems/sh20shieldgeneratorpack.svg",
    tier: "b",
  },
  {
    displayName: "Ballistic Shield",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbondCode: "none",
    internalName: "sh20ballisticshieldbackpack",
    imageUrl: "stratagems/sh20ballisticshieldbackpack.svg",
    tier: "d",
  },
  {
    displayName: "Portable Hellbomb",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbondCode: "warbond13",
    internalName: "portablehellbomb",
    imageUrl: "stratagems/portablehellbomb.svg",
    tier: "b",
  },
  {
    displayName: "Fast Recon Vehicle",
    type: "Stratagem",
    category: "Supply",
    tags: ["Vehicles"],
    warbondCode: "none",
    internalName: "fastreconvehicle",
    imageUrl: "stratagems/fastreconvehicle.svg",
    tier: "c",
  },
  {
    displayName: "Patriot Exosuit",
    type: "Stratagem",
    category: "Supply",
    tags: ["Vehicles"],
    warbondCode: "none",
    internalName: "exo45patriotexosuit",
    imageUrl: "stratagems/exo45patriotexosuit.svg",
    tier: "b",
  },
  {
    displayName: "Emancipator Exosuit",
    type: "Stratagem",
    category: "Supply",
    tags: ["Vehicles"],
    warbondCode: "none",
    internalName: "exo49emancipatorexosuit",
    imageUrl: "stratagems/exo49emancipatorexosuit.svg",
    tier: "s",
  },
  {
    displayName: "Eagle Strafing Run",
    type: "Stratagem",
    category: "Eagle",
    tags: ["Eagle"],
    warbondCode: "none",
    internalName: "eaglestrafingrun",
    imageUrl: "stratagems/eaglestrafingrun.svg",
    tier: "s",
  },
  {
    displayName: "Eagle Airstrike",
    type: "Stratagem",
    category: "Eagle",
    tags: ["Eagle"],
    warbondCode: "none",
    internalName: "eagleairstrike",
    imageUrl: "stratagems/eagleairstrike.svg",
    tier: "s",
  },
  {
    displayName: "Eagle Cluster Bomb",
    type: "Stratagem",
    category: "Eagle",
    tags: ["Eagle"],
    warbondCode: "none",
    internalName: "eagleclusterbomb",
    imageUrl: "stratagems/eagleclusterbomb.svg",
    tier: "a",
  },
  {
    displayName: "Eagle Napalm Strike",
    type: "Stratagem",
    category: "Eagle",
    tags: ["Eagle"],
    warbondCode: "none",
    internalName: "eaglenapalmstrike",
    imageUrl: "stratagems/eaglenapalmstrike.svg",
    tier: "s",
  },
  {
    displayName: "Eagle Smoke Strike",
    type: "Stratagem",
    category: "Eagle",
    tags: ["Eagle"],
    warbondCode: "none",
    internalName: "eaglesmokestrike",
    imageUrl: "stratagems/eaglesmokestrike.svg",
    tier: "d",
  },
  {
    displayName: "Eagle 110mm Rocket Pods",
    type: "Stratagem",
    category: "Eagle",
    tags: ["Eagle"],
    warbondCode: "none",
    internalName: "eagle110mmrocketpods",
    imageUrl: "stratagems/eagle110mmrocketpods.svg",
    tier: "b",
  },
  {
    displayName: "Eagle 500kg Bomb",
    type: "Stratagem",
    category: "Eagle",
    tags: ["Eagle"],
    warbondCode: "none",
    internalName: "eagle500kgbomb",
    imageUrl: "stratagems/eagle500kgbomb.svg",
    tier: "a",
  },
  {
    displayName: "Orbital Precision Strike",
    type: "Stratagem",
    category: "Orbital",
    tags: ["Orbital"],
    warbondCode: "none",
    internalName: "orbitalprecisionstrike",
    imageUrl: "stratagems/orbitalprecisionstrike.svg",
    tier: "c",
  },
  {
    displayName: "Orbital Gas Strike",
    type: "Stratagem",
    category: "Orbital",
    tags: ["Orbital"],
    warbondCode: "none",
    internalName: "orbitalgasstrike",
    imageUrl: "stratagems/orbitalgasstrike.svg",
    tier: "a",
  },
  {
    displayName: "Orbital EMS Strike",
    type: "Stratagem",
    category: "Orbital",
    tags: ["Orbital"],
    warbondCode: "none",
    internalName: "orbitalemsstrike",
    imageUrl: "stratagems/orbitalemsstrike.svg",
    tier: "d",
  },
  {
    displayName: "Orbital Smoke Strike",
    type: "Stratagem",
    category: "Orbital",
    tags: ["Orbital"],
    warbondCode: "none",
    internalName: "orbitalsmokestrike",
    imageUrl: "stratagems/orbitalsmokestrike.svg",
    tier: "d",
  },
  {
    displayName: "Orbital Airburst Strike",
    type: "Stratagem",
    category: "Orbital",
    tags: ["Orbital"],
    warbondCode: "none",
    internalName: "orbitalairburststrike",
    imageUrl: "stratagems/orbitalairburststrike.svg",
    tier: "b",
  },
  {
    displayName: "Orbital Railcannon Strike",
    type: "Stratagem",
    category: "Orbital",
    tags: ["Orbital"],
    warbondCode: "none",
    internalName: "orbitalrailcannonstrike",
    imageUrl: "stratagems/orbitalrailcannonstrike.svg",
    tier: "c",
  },
  {
    displayName: "Orbital Laser",
    type: "Stratagem",
    category: "Orbital",
    tags: ["Orbital"],
    warbondCode: "none",
    internalName: "orbitallaser",
    imageUrl: "stratagems/orbitallaser.svg",
    tier: "a",
  },
  {
    displayName: "Orbital Gatling Barrage",
    type: "Stratagem",
    category: "Orbital",
    tags: ["Orbital"],
    warbondCode: "none",
    internalName: "orbitalgatlingbarrage",
    imageUrl: "stratagems/orbitalgatlingbarrage.svg",
    tier: "a",
  },
  {
    displayName: "Orbital 120mm Barrage",
    type: "Stratagem",
    category: "Orbital",
    tags: ["Orbital"],
    warbondCode: "none",
    internalName: "orbital120mmhebarrage",
    imageUrl: "stratagems/orbital120mmhebarrage.svg",
    tier: "b",
  },
  {
    displayName: "Orbital 380mm Barrage",
    type: "Stratagem",
    category: "Orbital",
    tags: ["Orbital"],
    warbondCode: "none",
    internalName: "orbital380mmhebarrage",
    imageUrl: "stratagems/orbital380mmhebarrage.svg",
    tier: "c",
  },
  {
    displayName: "Orbital Walking Barrage",
    type: "Stratagem",
    category: "Orbital",
    tags: ["Orbital"],
    warbondCode: "none",
    internalName: "orbitalwalkingbarrage",
    imageUrl: "stratagems/orbitalwalkingbarrage.svg",
    tier: "c",
  },
  {
    displayName: "Orbital Napalm Barrage",
    type: "Stratagem",
    category: "Orbital",
    tags: ["Orbital"],
    warbondCode: "none",
    internalName: "orbitalnapalmbarrage",
    imageUrl: "stratagems/orbitalnapalmbarrage.svg",
    tier: "a",
  },
  {
    displayName: "Tesla Tower",
    type: "Stratagem",
    category: "Defense",
    tags: ["Emplacement"],
    warbondCode: "none",
    internalName: "teslatower",
    imageUrl: "stratagems/teslatower.svg",
    tier: "b",
  },
  {
    displayName: "Mortar Sentry",
    type: "Stratagem",
    category: "Defense",
    tags: ["Sentry"],
    warbondCode: "none",
    internalName: "mortarsentry",
    imageUrl: "stratagems/mortarsentry.svg",
    tier: "d",
  },
  {
    displayName: "EMS Mortar Sentry",
    type: "Stratagem",
    category: "Defense",
    tags: ["Sentry"],
    warbondCode: "none",
    internalName: "emsmortarsentry",
    imageUrl: "stratagems/emsmortarsentry.svg",
    tier: "c",
  },
  {
    displayName: "Machine Gun Sentry",
    type: "Stratagem",
    category: "Defense",
    tags: ["Sentry"],
    warbondCode: "none",
    internalName: "machinegunsentry",
    imageUrl: "stratagems/machinegunsentry.svg",
    tier: "a",
  },
  {
    displayName: "Gatling Sentry",
    type: "Stratagem",
    category: "Defense",
    tags: ["Sentry"],
    warbondCode: "none",
    internalName: "gatlingsentry",
    imageUrl: "stratagems/gatlingsentry.svg",
    tier: "b",
  },
  {
    displayName: "Flame Sentry",
    type: "Stratagem",
    category: "Defense",
    tags: ["Sentry"],
    warbondCode: "warbond12",
    internalName: "aflam40flamesentry",
    imageUrl: "stratagems/aflam40flamesentry.svg",
    tier: "c",
  },
  {
    displayName: "Laser Sentry",
    type: "Stratagem",
    category: "Defense",
    tags: ["Sentry"],
    warbondCode: "warbond17",
    internalName: "lasersentry",
    imageUrl: "stratagems/lasersentry.svg",
    tier: "c",
  },
  {
    displayName: "Autocannon Sentry",
    type: "Stratagem",
    category: "Defense",
    tags: ["Sentry"],
    warbondCode: "none",
    internalName: "autocannonsentry",
    imageUrl: "stratagems/autocannonsentry.svg",
    tier: "a",
  },
  {
    displayName: "Rocket Sentry",
    type: "Stratagem",
    category: "Defense",
    tags: ["Sentry"],
    warbondCode: "none",
    internalName: "rocketsentry",
    imageUrl: "stratagems/rocketsentry.svg",
    tier: "a",
  },
  {
    displayName: "Shield Generator Relay",
    type: "Stratagem",
    category: "Defense",
    tags: ["Emplacement"],
    warbondCode: "none",
    internalName: "shieldgeneratorrelay",
    imageUrl: "stratagems/shieldgeneratorrelay.svg",
    tier: "b",
  },
  {
    displayName: "HMG Emplacement",
    type: "Stratagem",
    category: "Defense",
    tags: ["Emplacement"],
    warbondCode: "none",
    internalName: "hmgemplacement",
    imageUrl: "stratagems/hmgemplacement.svg",
    tier: "b",
  },
  {
    displayName: "Anti-Tank Emplacement",
    type: "Stratagem",
    category: "Defense",
    tags: ["Emplacement"],
    warbondCode: "warbond12",
    internalName: "eat12antitankemplacement",
    imageUrl: "stratagems/eat12antitankemplacement.svg",
    tier: "b",
  },
  {
    displayName: "Grenadier Battlement",
    type: "Stratagem",
    category: "Defense",
    tags: ["Emplacement"],
    warbondCode: "none",
    internalName: "grenadierbattlement",
    imageUrl: "stratagems/grenadierbattlement.svg",
    tier: "c",
  },
  {
    displayName: "Anti-Tank Mines",
    type: "Stratagem",
    category: "Defense",
    tags: ["Emplacement"],
    warbondCode: "none",
    internalName: "antitankmines",
    imageUrl: "stratagems/antitankmines.svg",
    tier: "d",
  },
  {
    displayName: "Anti-Personnel Mines",
    type: "Stratagem",
    category: "Defense",
    tags: ["Emplacement"],
    warbondCode: "none",
    internalName: "antipersonnelminefield",
    imageUrl: "stratagems/antipersonnelminefield.svg",
    tier: "d",
  },
  {
    displayName: "Gas Mines",
    type: "Stratagem",
    category: "Defense",
    tags: ["Emplacement"],
    warbondCode: "none",
    internalName: "gasmines",
    imageUrl: "stratagems/gasmines.svg",
    tier: "c",
  },
  {
    displayName: "Incendiary Mines",
    type: "Stratagem",
    category: "Defense",
    tags: ["Emplacement"],
    warbondCode: "none",
    internalName: "incendiarymines",
    imageUrl: "stratagems/incendiarymines.svg",
    tier: "c",
  },
];