export function getThrowable(displayName) {
  return THROWABLES.find((item) => item.displayName === displayName);
}

export const THROWABLES = [
  {
    displayName: "G-12 High Explosive",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "none",
    internalName: "g12highexplosivegrenade",
    imageUrl: "equipment/g12highexplosivegrenade.png",
    tier: "a",
  },
  {
    displayName: "G-4 Gas",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond10",
    internalName: "g4gasgrenade",
    imageUrl: "equipment/g4gasgrenade.png",
    tier: "s",
  },
  {
    displayName: "K-2 Throwing Knife",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond8",
    internalName: "k2throwingknife",
    imageUrl: "equipment/k2throwingknife.png",
    tier: "d",
  },
  {
    displayName: "G-6 Frag",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond3",
    internalName: "g6fraggrenade",
    imageUrl: "equipment/g6fraggrenade.png",
    tier: "a",
  },
  {
    displayName: "G-16 Impact",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond3",
    internalName: "g16impactgrenade",
    imageUrl: "equipment/g16impactgrenade.png",
    tier: "a",
  },
  {
    displayName: "G-3 Smoke",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond3",
    internalName: "g3smokegrenade",
    imageUrl: "equipment/g3smokegrenade.png",
    tier: "d",
  },
  {
    displayName: "G-10 Incendiary",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond4",
    internalName: "g10incendiarygrenade",
    imageUrl: "equipment/g10incendiarygrenade.png",
    tier: "a",
  },
  {
    displayName: "G-23 Stun",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond5",
    internalName: "g23stungrenade",
    imageUrl: "equipment/g23stungrenade.png",
    tier: "c",
  },
  {
    displayName: "G-123 Thermite",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond6",
    internalName: "g123thermitegrenade",
    imageUrl: "equipment/g123thermitegrenade.png",
    tier: "s",
  },
  {
    displayName: "G-13 Incendiary Impact",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond7",
    internalName: "g13incendiaryimpact",
    imageUrl: "equipment/g13incendiaryimpact.png",
    tier: "a",
  },
  {
    displayName: "G-50 Seeker",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond13",
    internalName: "g50seeker",
    imageUrl: "equipment/g50seeker.png",
    tier: "c",
  },
  {
    displayName: "Dynamite",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond14",
    internalName: "ted63throwabledynamite",
    imageUrl: "equipment/ted63throwabledynamite.png",
    tier: "b",
  },
  {
    displayName: "G-142 Pyrotech",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond15",
    internalName: "g142pyrotech",
    imageUrl: "equipment/g142pyrotech.png",
    tier: "a",
  },
  {
    displayName: "G-109 Urchin",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond16",
    internalName: "g109urchin",
    imageUrl: "equipment/g109urchin.png",
    tier: "c",
  },
  {
    displayName: "G-31 Arc",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond17",
    internalName: "g31arc",
    imageUrl: "equipment/g31arc.png",
    tier: "b",
  },
  {
    displayName: "G-7 Pineapple",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond20",
    internalName: "g7pineapple",
    imageUrl: "equipment/g7pineapple.png",
    tier: "c",
  },
];
