export function getWarbond(displayName) {
  return WARBONDS.find((item) => item.displayName === displayName);
}
export function getWarbondByCode(warbondCode) {
  return WARBONDS.find((item) => item.warbondCode === warbondCode);
}

const WARBONDS = [
  {
    displayName: "None",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "none",
    internalName: "noneWB",
    imageUrl: "",
    tier: "d",
  },
  {
    displayName: "Super Citizen Preorder",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond0",
    internalName: "superCitizenWB",
    imageUrl: "",
    tier: "b",
  },
  {
    displayName: "Super Store",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond1",
    internalName: "superStoreWB",
    imageUrl: "",
    tier: "a",
  },
  {
    displayName: "Helldivers Mobilize",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond3",
    internalName: "helldiversMobilizeWB",
    imageUrl: "warbonds/helldiversMobilizeWB.png",
    tier: "s",
  },
  {
    displayName: "Steeled Veterans",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond4",
    internalName: "steeledVeteransWB",
    imageUrl: "warbonds/steeledVeteransWB.png",
    tier: "a",
  },
  {
    displayName: "Cutting Edge",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond5",
    internalName: "cuttingEdgeWB",
    imageUrl: "warbonds/cuttingEdgeWB.png",
    tier: "a",
  },
  {
    displayName: "Democratic Detonation",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond6",
    internalName: "democraticDetonationWB",
    imageUrl: "warbonds/democraticDetonationWB.png",
    tier: "s",
  },
  {
    displayName: "Polar Patriots",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond7",
    internalName: "polarPatriotsWB",
    imageUrl: "warbonds/polarPatriotsWB.png",
    tier: "b",
  },
  {
    displayName: "Viper Commandos",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond8",
    internalName: "viperCommandosWB",
    imageUrl: "warbonds/viperCommandosWB.png",
    tier: "b",
  },
  {
    displayName: "Freedom's Flame",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond9",
    internalName: "freedomsFlameWB",
    imageUrl: "warbonds/freedomsFlameWB.png",
    tier: "b",
  },
  {
    displayName: "Chemical Agents",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond10",
    internalName: "chemicalAgentsWB",
    imageUrl: "warbonds/chemicalAgentsWB.png",
    tier: "b",
  },
  {
    displayName: "Truth Enforcers",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond11",
    internalName: "truthEnforcersWB",
    imageUrl: "warbonds/truthEnforcersWB.png",
    tier: "b",
  },
  {
    displayName: "Urban Legends",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond12",
    internalName: "urbanLegendsWB",
    imageUrl: "warbonds/urbanLegendsWB.png",
    tier: "b",
  },
  {
    displayName: "Servants of Freedom",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond13",
    internalName: "servantsOfFreedomWB",
    imageUrl: "warbonds/servantsOfFreedomWB.png",
    tier: "a",
  },
  {
    displayName: "Borderline Justice",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond14",
    internalName: "borderlineJusticeWB",
    imageUrl: "warbonds/borderlineJusticeWB.png",
    tier: "b",
  },
  {
    displayName: "Masters of Ceremony",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond15",
    internalName: "mastersOfCeremonyWB",
    imageUrl: "warbonds/mastersOfCeremonyWB.png",
    tier: "c",
  },
  {
    displayName: "Force of Law",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond16",
    internalName: "forceOfLawWB",
    imageUrl: "warbonds/forceOfLawWB.png",
    tier: "b",
  },
  {
    displayName: "Control Group",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond17",
    internalName: "controlGroupWB",
    imageUrl: "warbonds/controlGroupWB.png",
    tier: "a",
  },
  {
    displayName: "ODST",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond19",
    internalName: "odstWB",
    imageUrl: "warbonds/odstWB.png",
    tier: "b",
  },
  {
    displayName: "Dust Devils",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond20",
    internalName: "dustdevilsWB",
    imageUrl: "warbonds/dustdevilsWB.png",
    tier: "b",
  },
];
